import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:qa_genie/core/error/exceptions.dart';
import 'package:qa_genie/core/utils/priority_utils.dart';
import 'package:qa_genie/domain/entities/finalized_test_case.dart';
import 'package:qa_genie/features/export/adapters/csv_adapter.dart';
import 'package:qa_genie/features/export/adapters/pdf_adapter.dart';
import 'package:qa_genie/features/export/common/export_mapper.dart';
import 'package:qa_genie/features/export/adapters/json_adapter.dart';
import 'package:qa_genie/features/export/adapters/excel_adapter.dart';
import 'package:qa_genie/domain/usecases/export_validation_service.dart';
import 'package:qa_genie/features/export/folder/export_folder_service.dart';

class ExportTestCasesUseCase {
  const ExportTestCasesUseCase();

  // ============================================================
  // MAIN EXECUTION (moduleName and featureName are now optional)
  // ============================================================

  Future<void> execute({
    required String type,
    required List<FinalizedTestCase> cases,
    String? moduleName,
    String? featureName,
  }) async {
    try {
      _validateOrThrow(cases);

      // If moduleName/featureName not provided, extract from first test case
      final effectiveModule =
          moduleName ?? (cases.isNotEmpty ? cases.first.module : 'Unknown');
      final effectiveFeature =
          featureName ?? (cases.isNotEmpty ? cases.first.feature : 'Unknown');

      final normalizedType = type.trim().toLowerCase();
      final safeModule = _safeModulePrefix(effectiveModule);
      final code = _shortCode();
      final fileName = 'TC_${safeModule}_${normalizedType}_$code';

      switch (normalizedType) {
        case 'excel':
          await ExcelAdapter.export(
            cases,
            fileName: fileName,
            moduleName: effectiveModule,
            featureName: effectiveFeature,
          );
          return;
        case 'jira':
          await CsvAdapter.export(
            cases,
            fileName: fileName,
            moduleName: effectiveModule,
            featureName: effectiveFeature,
          );
          return;
        case 'xray':
          await JsonAdapter.export(
            cases,
            fileName: fileName,
            moduleName: effectiveModule,
            featureName: effectiveFeature,
          );
          return;
        case 'pdf':
          await PdfAdapter.export(
            cases,
            fileName: fileName,
            moduleName: effectiveModule,
            featureName: effectiveFeature,
          );
          return;
        default:
          throw ExportException('Unsupported export format: $type');
      }
    } catch (e) {
      throw ExportException('Export execution failed: $e');
    }
  }

  // ============================================================
  // SUMMARY REPORT (moduleName and featureName optional)
  // ============================================================

  Future<void> exportSummaryReport({
    required List<FinalizedTestCase> cases,
    String? moduleName,
    String? featureName,
    required String platform,
    required String testerName,
    required String environment,
  }) async {
    try {
      final effectiveModule =
          moduleName ?? (cases.isNotEmpty ? cases.first.module : 'Unknown');
      final effectiveFeature =
          featureName ?? (cases.isNotEmpty ? cases.first.feature : 'Unknown');

      final data = ExportMapper.toSummaryReport(
        cases,
        effectiveModule,
        effectiveFeature,
        platform,
        testerName,
        environment,
      );

      final pdf = pw.Document();
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(28),
          build: (context) => [
            _buildHeader(data),
            pw.SizedBox(height: 20),
            _buildExecutionSummary(data),
            pw.SizedBox(height: 20),
            _buildPriorityBreakdown(data),
            pw.SizedBox(height: 20),
            _buildDetailedResults(data['details'] as List),
            pw.SizedBox(height: 24),
            pw.Center(
              child: pw.Text(
                'Generated by QA Genie',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey),
              ),
            ),
          ],
        ),
      );

      final dir = await ExportFolderService.getPersistentDirectory();
      final code = _shortCode();
      final safeModule = _safeModulePrefix(effectiveModule);
      final file = File('${dir.path}/TSR_${safeModule}_$code.pdf');
      await file.writeAsBytes(await pdf.save());
      await Share.shareXFiles([XFile(file.path)]);
    } catch (e) {
      throw ExportException('Summary export failed: $e');
    }
  }

  // ============================================================
  // HEADER
  // ============================================================

  pw.Widget _buildHeader(Map<String, dynamic> data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Test Summary Report',
          style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.Text('Suite: ${data['suiteName']}'),
        pw.Text('Platform: ${data['platform']}'),
        pw.Text('Date: ${data['date']}'),
        if ((data['testerName'] ?? '').toString().isNotEmpty)
          pw.Text('Tester: ${data['testerName']}'),
        if ((data['environment'] ?? '').toString().isNotEmpty)
          pw.Text('Environment: ${data['environment']}'),
      ],
    );
  }

  // ============================================================
  // EXECUTION SUMMARY
  // ============================================================

  pw.Widget _buildExecutionSummary(Map<String, dynamic> data) {
    final labels = [
      'Total',
      'Passed',
      'Failed',
      'Blocked',
      'Not Executed',
      'Pass Rate',
    ];
    final keys = [
      'total',
      'passed',
      'failed',
      'blocked',
      'notExecuted',
      'passRate',
    ];

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Execution Summary',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14),
        ),
        pw.SizedBox(height: 8),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey200),
              children: [
                _cell('Metric', bold: true),
                _cell('Value', bold: true),
              ],
            ),
            for (int i = 0; i < labels.length; i++)
              pw.TableRow(
                children: [
                  _cell(labels[i]),
                  _cell(
                    keys[i] == 'passRate'
                        ? '${data[keys[i]]}%'
                        : '${data[keys[i]]}',
                  ),
                ],
              ),
          ],
        ),
      ],
    );
  }

  // ============================================================
  // PRIORITY BREAKDOWN
  // ============================================================

  pw.Widget _buildPriorityBreakdown(Map<String, dynamic> data) {
    final breakdown = data['priorityBreakdown'] as Map<String, dynamic>;
    final items = breakdown.entries.map((e) => '${e.key}: ${e.value}').toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Priority Breakdown',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14),
        ),
        pw.SizedBox(height: 8),
        for (final item in items)
          pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 4),
            child: pw.Text(item, style: const pw.TextStyle(fontSize: 10)),
          ),
      ],
    );
  }

  // ============================================================
  // DETAILED RESULTS
  // ============================================================

  pw.Widget _buildDetailedResults(List<dynamic> details) {
    if (details.isEmpty) return pw.Container();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Detailed Results',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14),
        ),
        pw.SizedBox(height: 8),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          columnWidths: {
            0: const pw.FixedColumnWidth(90),
            1: const pw.FlexColumnWidth(3),
            2: const pw.FixedColumnWidth(60),
            3: const pw.FixedColumnWidth(80),
            4: const pw.FlexColumnWidth(2),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey200),
              children: [
                _cell('ID', bold: true),
                _cell('Title', bold: true),
                _cell('Priority', bold: true),
                _cell('Status', bold: true),
                _cell('Actual Result', bold: true),
              ],
            ),
            for (final item in details)
              pw.TableRow(
                children: [
                  _cell(item['id']?.toString() ?? ''),
                  _cell(item['title']?.toString() ?? ''),
                  _cell(PriorityUtils.normalize(item['priority']?.toString())),
                  _cell(item['status']?.toString() ?? 'NOT EXECUTED'),
                  _cell(item['actualResult']?.toString() ?? ''),
                ],
              ),
          ],
        ),
      ],
    );
  }

  // ============================================================
  // CELL
  // ============================================================

  pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }

  // ============================================================
  // VALIDATION
  // ============================================================

  void _validateOrThrow(List<FinalizedTestCase> cases) {
    final validation = ExportValidationService.validate(cases);
    if (!validation.isValid) {
      throw ExportException(validation.errors.join('\n'));
    }
  }

  // ============================================================
  // FILE PREFIX
  // ============================================================

  String _safeModulePrefix(String moduleName) {
    final cleaned = moduleName
        .replaceAll(RegExp(r'[^A-Za-z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_+|_+$'), '');
    if (cleaned.isEmpty) return 'MODULE';
    return cleaned.length > 20 ? cleaned.substring(0, 20) : cleaned;
  }

  // ============================================================
  // RANDOM CODE
  // ============================================================

  String _shortCode() {
    final value = DateTime.now().millisecondsSinceEpoch % 10000;
    return value.toString().padLeft(4, '0');
  }
}
