class LegalDocuments {
  static const String privacyPolicy = '''
QA Genie Privacy Policy
Last updated: June 2026

QA Genie (“we,” “us,” “our”) is committed to protecting your privacy and ensuring transparency in our data practices. We operate on a philosophy of data minimization, collecting only what is strictly necessary to provide you with our test automation and generation services.

1. Information We Collect:
- Account Identity: When you authenticate via Google Sign-In, we collect your Firebase UID and email address. We do not store your password. For anonymous users, we assign a temporary 'GuestN' identifier locally.
- Usage Metrics: We track generation and export counts to manage fair-use limits. This data is stored in your secure usage document in our database.
- Diagnostic Information: If you choose to submit a report via our "Report Issue" feature, we collect optional diagnostic information including device model, app version, and platform to help our team troubleshoot and resolve issues efficiently.
- AI Interaction: Generation prompts and AI-provided outputs are processed securely through our AI partner, DeepSeek. To ensure service reliability, we audit these interactions.

2. Third-Party Services:
- We utilize Firebase (Google) for authentication, database synchronization, and analytics.
- We utilize Google AdMob to provide free-tier users access to features via rewarded advertisements. AdMob may collect device-specific advertising identifiers to deliver personalized ads.

3. Data Storage & Security:
- Data is synced via Firebase and stored locally on your device in our secure SQLite database. We do not sell your personal data to third parties.

4. Your Rights:
- You may request account deletion and data removal at any time by contacting our support team through the "Report an Issue" menu in the app. Upon request, we will permanently delete your associated records from our cloud database.''';

  static const String termsOfUse = '''
Terms of Service
Last updated: June 2026

By installing and using QA Genie, you agree to the following terms and conditions:

1. Service Purpose: QA Genie is intended to serve as an AI-powered tool for professional quality assurance and test automation. Usage of this tool is restricted to these stated purposes.

2. AI Reliability and Validation: Test cases generated by QA Genie are provided "as-is." AI models are probabilistic and may occasionally produce inconsistencies. You are solely responsible for reviewing, validating, and ensuring the suitability of any AI-generated test scenarios before incorporating them into your official test suites, development environment, or production pipelines.

3. Fair Use and Limitations: We provide generation and export capacities based on your account tier (Core or Pro). You agree to respect these limits. Automated abuse, scraping of our services, or attempts to bypass our quota enforcement mechanisms are strictly prohibited and will result in account suspension.

4. Account Responsibility: You are responsible for maintaining the security of your account. Access to "Pro" tier features is determined by our cloud-authoritative subscription verification systems. Any account found to be circumventing these systems may be terminated without notice.

5. Modifications: We reserve the right to update these terms to reflect changes in our services. Continued use of the application after such changes constitutes your acceptance of the updated terms.''';

  static const String aiDisclaimer = '''
AI Content Disclaimer
Last updated: June 2026

QA Genie utilizes advanced artificial intelligence (AI) models to assist in the creation of test scenarios, test steps, and quality assurance documentation. While our engine is engineered to provide high-quality, relevant test data, it is imperative to understand the following:

1. Probabilistic Nature: AI models function by predicting information based on learned patterns rather than absolute, deterministic logic. Consequently, generated content may contain errors, logical inaccuracies, or context-specific hallucinations.

2. Human Oversight: QA Genie is a tool designed to accelerate, not replace, the work of Quality Assurance professionals. We strongly recommend that all generated content is subjected to rigorous manual review and validation by a qualified QA engineer before being utilized in critical software development life cycles (SDLC), testing environments, or production systems.

3. Liability Limitations: QA Genie disclaims all warranties, express or implied, regarding the accuracy, completeness, or suitability of generated test cases. We shall not be held liable for any defects, damages, or service interruptions that may arise from the use of content generated by our AI engine. By using this tool, you acknowledge that you are responsible for the outcome of any testing strategy that incorporates AI-generated content.''';

  static const String adsPolicy = '''
Ads & Monetization Policy
Last updated: June 2026

QA Genie operates on a freemium model to ensure our AI generation services remain sustainable.

1. Rewarded Advertising: Core tier users may unlock additional generation and export capacity by choosing to engage with rewarded video advertisements delivered through the Google AdMob network. 

2. Ad Personalization: By selecting the option to view rewarded ads, you consent to Google AdMob’s collection and use of device-level identifiers (such as the advertising identifier on Android) to provide personalized advertisement experiences. These identifiers are processed according to Google’s AdMob Privacy Policy. 

3. Transparency: We only serve rewarded advertisements when you choose to initiate them. We do not implement obtrusive, unexpected interstitial or banner advertising that disrupts your core workflow.

4. Pro Tiers: Users who opt for the "Pro" tier experience receive an ad-free service, bypassing all ad-supported generation and export limitations. Pro tier access is managed via our internal subscription verification logic. If you believe your Pro status is not being correctly applied, please contact our support team immediately through the "Report an Issue" function for investigation.''';
}
