import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:qa_genie/core/error/exceptions.dart';
import 'package:qa_genie/domain/entities/finalized_test_case.dart';
import 'package:qa_genie/features/export/common/export_mapper.dart';
import 'package:qa_genie/features/export/folder/export_folder_service.dart';
// ============================================================
// FILE: lib/features/export/adapters/pdf_adapter.dart
// ============================================================

/// ===============================================================
///
/// PDF ADAPTER (Hardenened vNext)
///
/// PURPOSE:
/// - Traditional QA testcase format
/// - Enterprise-readable printable export
/// - Paginated deterministic rendering
///
/// ARCHITECTURAL ROLE:
/// - Pure reader of FinalizedTestCase.
/// - Hardened pagination to prevent RangeError.
/// - Flow-based rendering for long text safety.
///
/// ===============================================================
class PdfAdapter {
  const PdfAdapter._();

  // ============================================================
  // EXPORT
  // ============================================================

  static Future<void> export(
    List<FinalizedTestCase> cases, {
    required String fileName,
    required String moduleName,
    required String featureName,
  }) async {
    try {
      /// Forensic logic: Direct consumption of FinalizedTestCase to ensure
      /// session edits (actualResult/status) are reflected instantly.
      final mapped = ExportMapper.toPdf(cases);

      final pdf = pw.Document();

      /// Hardening: Use a single MultiPage document to allow the pdf library
      /// to handle row wrapping and pagination deterministically.
      /// Manual chunking is removed to prevent RangeError during sublist ops.
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4.landscape,
          margin: const pw.EdgeInsets.all(24),
          header: (context) => _header(moduleName, featureName),
          footer: (context) => _footer(context),
          build: (context) => [pw.SizedBox(height: 10), _table(mapped)],
        ),
      );

      final dir = await ExportFolderService.getTempDirectory();

      final file = File('${dir.path}/$fileName.pdf');

      await file.writeAsBytes(await pdf.save());

      await Share.shareXFiles([XFile(file.path)]);
    } catch (e) {
      throw ExportException('PDF export failed: $e');
    }
  }

  // ============================================================
  // HEADER
  // ============================================================

  static pw.Widget _header(String module, String feature) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Test Cases - $module',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(
              'Feature: $feature',
              style: const pw.TextStyle(fontSize: 10),
            ),
          ],
        ),
        pw.Divider(thickness: 0.5),
      ],
    );
  }

  // ============================================================
  // FOOTER
  // ============================================================

  static pw.Widget _footer(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 10),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by QA Genie',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(fontSize: 8),
          ),
        ],
      ),
    );
  }

  // ============================================================
  // TABLE
  // ============================================================

  static pw.Widget _table(List<Map<String, dynamic>> rows) {
    return pw.Table.fromTextArray(
      headers: const [
        'ID',
        'Title',
        'Preconditions',
        'Steps',
        'Test Data',
        'Expected Result',
        'Actual Result',
        'Status',
        'Priority',
      ],

      data: rows
          .map(
            (row) => [
              '${row['ID'] ?? ''}',
              '${row['Title'] ?? ''}',
              '${row['Preconditions'] ?? ''}',
              '${row['Steps'] ?? ''}',
              '${row['Test Data'] ?? ''}',
              '${row['Expected Result'] ?? ''}',
              '${row['Actual Result'] ?? ''}',
              '${row['Status'] ?? ''}',
              '${row['Priority'] ?? ''}',
            ],
          )
          .toList(),

      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8),

      cellStyle: const pw.TextStyle(fontSize: 7),

      border: pw.TableBorder.all(width: 0.4, color: PdfColors.grey),

      cellAlignment: pw.Alignment.topLeft,

      headerAlignment: pw.Alignment.center,

      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),

      /// Hardening: Deterministic column widths in landscape to prevent overflow.
      columnWidths: {
        0: const pw.FixedColumnWidth(40),
        1: const pw.FlexColumnWidth(3),
        2: const pw.FlexColumnWidth(2),
        3: const pw.FlexColumnWidth(4),
        4: const pw.FlexColumnWidth(2),
        5: const pw.FlexColumnWidth(3),
        6: const pw.FlexColumnWidth(3),
        7: const pw.FixedColumnWidth(55),
        8: const pw.FixedColumnWidth(45),
      },
    );
  }
}
