import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:qa_app/data/models/test_case_model.dart';
import 'package:qa_app/features/export/common/export_mapper.dart';

class PdfAdapter {
  static Future<void> export(
    List<TestCaseModel> cases, {
    required String fileName,
    required String moduleName,
    required String featureName,
  }) async {
    final mapped = ExportMapper.toPdf(cases.map((tc) => tc.copy()).toList());
    final pdf = pw.Document();
    const int rowsPerPage = 18;
    final totalPages = mapped.isEmpty
        ? 1
        : (mapped.length / rowsPerPage).ceil();

    for (int page = 0; page < totalPages; page++) {
      final start = page * rowsPerPage;
      final end = (start + rowsPerPage).clamp(0, mapped.length);
      final chunk = mapped.sublist(start, end);

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(30),
          build: (ctx) => [
            pw.Text(
              'Test Cases - $moduleName · $featureName',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 16),
            pw.Table.fromTextArray(
              headers: [
                'ID',
                'Title',
                'Preconditions',
                'Steps',
                'Test Data',
                'Expected Result',
                'Priority',
              ],
              data: chunk
                  .map(
                    (row) => [
                      (row['ID'] ?? '').toString(),
                      (row['Title'] ?? '').toString(),
                      (row['Preconditions'] ?? '').toString(),
                      (row['Steps'] ?? '').toString(),
                      (row['Test Data'] ?? '').toString(),
                      (row['Expected Result'] ?? '').toString(),
                      (row['Priority'] ?? '').toString(),
                    ],
                  )
                  .toList(),
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 8,
              ),
              cellStyle: const pw.TextStyle(fontSize: 6),
              columnWidths: {
                0: const pw.FixedColumnWidth(40),  // ID
                1: const pw.FlexColumnWidth(3),   // Title
                2: const pw.FlexColumnWidth(2),   // Preconditions
                3: const pw.FlexColumnWidth(4),   // Steps
                4: const pw.FlexColumnWidth(2),   // Test Data
                5: const pw.FlexColumnWidth(3),   // Expected Result
                6: const pw.FixedColumnWidth(45), // Priority
              },
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.grey200,
              ),
              border: pw.TableBorder.all(width: 0.5),
              cellAlignment: pw.Alignment.topLeft,
              headerAlignment: pw.Alignment.center,
            ),
            pw.SizedBox(height: 20),
            if (page == totalPages - 1)
              pw.Center(
                child: pw.Text(
                  'Generated by QA Genie',
                  style: pw.TextStyle(fontSize: 8, color: PdfColors.grey),
                ),
              ),
          ],
        ),
      );
    }

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$fileName.pdf');
    await file.writeAsBytes(await pdf.save());
    await Share.shareXFiles([XFile(file.path)]);
  }
}
