import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:flutter/foundation.dart';
import 'package:share_plus/share_plus.dart';
import 'package:qa_genie/core/error/exceptions.dart';
import 'package:qa_genie/engine/utils/pdf_text_sanitizer.dart';
import 'package:qa_genie/domain/entities/finalized_test_case.dart';
import 'package:qa_genie/features/export/common/export_mapper.dart';
import 'package:qa_genie/features/export/folder/export_folder_service.dart';

/// PDF ADAPTER
/// Generates a professional PDF table with pagination.
class PdfAdapter {
  const PdfAdapter._();

  static Future<void> export(
    List<FinalizedTestCase> cases, {
    required String fileName,
    required String moduleName,
    required String featureName,
    bool hideEmptyColumns = false,
  }) async {
    final startTime = DateTime.now();
    debugPrint('📄 PDF_ADAPTER: Started export for ${cases.length} cases');
    try {
      final mapped = ExportMapper.toPdf(cases);
      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4.landscape,
          margin: const pw.EdgeInsets.all(24),
          header: (context) => _header(moduleName, featureName),
          footer: (context) => _footer(context),
          build: (context) => [pw.SizedBox(height: 10), _table(mapped, hideEmptyColumns: hideEmptyColumns)],
        ),
      );

      final dir = await ExportFolderService.getTempDirectory();
      final file = File('${dir.path}/$fileName.pdf');
      await file.writeAsBytes(await pdf.save());
      await Share.shareXFiles([XFile(file.path)]);
      final duration = DateTime.now().difference(startTime).inMilliseconds;
      debugPrint('✅ PDF_ADAPTER: Success in ${duration}ms');
    } catch (e, stack) {
      final duration = DateTime.now().difference(startTime).inMilliseconds;
      debugPrint('❌ PDF_ADAPTER: Failed after ${duration}ms');
      debugPrint('❌ PDF_ADAPTER error: $e');
      debugPrint('❌ PDF_ADAPTER stack: $stack');
      throw ExportException('PDF export failed: $e');
    }
  }

  static pw.Widget _header(String module, String feature) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          PdfTextSanitizer.sanitize('TEST CASES'),
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Row(
          children: [
            pw.Text(
              PdfTextSanitizer.sanitize('Module  : '),
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.Text(
              PdfTextSanitizer.sanitize(module),
              style: const pw.TextStyle(fontSize: 10),
            ),
          ],
        ),
        pw.Row(
          children: [
            pw.Text(
              PdfTextSanitizer.sanitize('Feature : '),
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.Text(
              PdfTextSanitizer.sanitize(feature),
              style: const pw.TextStyle(fontSize: 10),
            ),
          ],
        ),
        pw.Divider(thickness: 0.5),
      ],
    );
  }

  static pw.Widget _footer(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 10),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            PdfTextSanitizer.sanitize('Generated by QA Genie'),
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey),
          ),
          pw.Text(
            PdfTextSanitizer.sanitize(
              'Page ${context.pageNumber} of ${context.pagesCount}',
            ),
            style: const pw.TextStyle(fontSize: 8),
          ),
        ],
      ),
    );
  }

  static pw.Widget _table(List<Map<String, dynamic>> rows, {bool hideEmptyColumns = false}) {
    if (hideEmptyColumns) {
      return pw.Table.fromTextArray(
        headers: const [
          'Test Case ID',
          'Title',
          'Preconditions',
          'Steps',
          'Test Data',
          'Expected Result',
          'Priority',
        ],
        data: rows
            .map(
              (row) => [
                PdfTextSanitizer.sanitize(
                  _toString(row['ID'] ?? row['Test Case ID'] ?? ''),
                ),
                PdfTextSanitizer.sanitize(_toString(row['Title'])),
                PdfTextSanitizer.sanitize(_toString(row['Preconditions'])),
                PdfTextSanitizer.sanitize(_toString(row['Steps'])),
                PdfTextSanitizer.sanitize(_toString(row['Test Data'])),
                PdfTextSanitizer.sanitize(_toString(row['Expected Result'])),
                PdfTextSanitizer.sanitize(_toString(row['Priority'])),
              ],
            )
            .toList(),
        headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8),
        cellStyle: const pw.TextStyle(fontSize: 7),
        border: pw.TableBorder.all(width: 0.4, color: PdfColors.grey),
        cellAlignment: pw.Alignment.topLeft,
        headerAlignment: pw.Alignment.center,
        headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
        cellPadding: const pw.EdgeInsets.all(6),
        columnWidths: {
          0: const pw.FixedColumnWidth(45),
          1: const pw.FlexColumnWidth(4),
          2: const pw.FlexColumnWidth(2),
          3: const pw.FlexColumnWidth(4),
          4: const pw.FlexColumnWidth(2),
          5: const pw.FlexColumnWidth(3),
          6: const pw.FixedColumnWidth(45),
        },
      );
    }
    return pw.Table.fromTextArray(
      headers: const [
        'Test Case ID',
        'Title',
        'Preconditions',
        'Steps',
        'Test Data',
        'Expected Result',
        'Actual Result',
        'Status',
        'Priority',
      ],
      data: rows
          .map(
            (row) => [
              // ID fallback: ExportMapper uses 'ID' key, but we also accept 'Test Case ID'
              PdfTextSanitizer.sanitize(
                _toString(row['ID'] ?? row['Test Case ID'] ?? ''),
              ),
              PdfTextSanitizer.sanitize(_toString(row['Title'])),
              PdfTextSanitizer.sanitize(_toString(row['Preconditions'])),
              PdfTextSanitizer.sanitize(_toString(row['Steps'])),
              PdfTextSanitizer.sanitize(_toString(row['Test Data'])),
              PdfTextSanitizer.sanitize(_toString(row['Expected Result'])),
              PdfTextSanitizer.sanitize(_toString(row['Actual Result'])),
              PdfTextSanitizer.sanitize(_toString(row['Status'])),
              PdfTextSanitizer.sanitize(_toString(row['Priority'])),
            ],
          )
          .toList(),
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8),
      cellStyle: const pw.TextStyle(fontSize: 7),
      border: pw.TableBorder.all(width: 0.4, color: PdfColors.grey),
      cellAlignment: pw.Alignment.topLeft,
      headerAlignment: pw.Alignment.center,
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
      cellPadding: const pw.EdgeInsets.all(6),
      columnWidths: {
        0: const pw.FixedColumnWidth(45),
        1: const pw.FlexColumnWidth(3),
        2: const pw.FlexColumnWidth(2),
        3: const pw.FlexColumnWidth(4),
        4: const pw.FlexColumnWidth(2),
        5: const pw.FlexColumnWidth(3),
        6: const pw.FlexColumnWidth(3),
        7: const pw.FixedColumnWidth(55),
        8: const pw.FixedColumnWidth(45),
      },
    );
  }

  static String _toString(dynamic value) {
    return (value ?? '').toString();
  }
}
