import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final aiMlDomain = DomainOntology(
  id: 'ai_ml',
  displayName: 'AI / ML',
  synonyms: [
    'ai', 'ml', 'machine learning', 'artificial intelligence',
    'model', 'training', 'prediction', 'deep learning', 'llm',
  ],
  entities: {
    'model': EntityDef(
      id: 'model',
      displayName: 'Model',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Model ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'model-cls-v1-42',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Model name',
          type: PropertyType.string,
          required: true,
          example: 'Customer Churn Classifier',
        ),
        PropertyDef(
          name: 'version',
          displayName: 'Version',
          type: PropertyType.string,
          required: true,
          example: '2.1.0',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Model type',
          type: PropertyType.enum_,
          required: true,
          enumValues: [
            'Classification', 'Regression', 'Clustering',
            'NLP', 'Computer Vision', 'Generative',
            'Reinforcement Learning',
          ],
          example: 'Classification',
        ),
        PropertyDef(
          name: 'framework',
          displayName: 'Framework',
          type: PropertyType.enum_,
          required: true,
          enumValues: [
            'TensorFlow', 'PyTorch', 'Scikit-learn',
            'XGBoost', 'Keras', 'JAX', 'ONNX',
          ],
          example: 'PyTorch',
        ),
        PropertyDef(
          name: 'accuracy',
          displayName: 'Accuracy',
          type: PropertyType.percent,
          required: true,
          example: '94.7',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'latency',
          displayName: 'Latency (ms)',
          type: PropertyType.integer,
          example: '45',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Model status',
          type: PropertyType.enum_,
          enumValues: [
            'Active', 'Inactive', 'Pending',
            'Training', 'Deployed', 'Failed',
            'Archived', 'Evaluating',
          ],
          example: 'Active',
        ),
        PropertyDef(
          name: 'modelSize',
          displayName: 'Model size (MB)',
          type: PropertyType.number,
          example: '256.3',
        ),
      ],
    ),
    'dataset': EntityDef(
      id: 'dataset',
      displayName: 'Dataset',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Dataset ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'ds-customer-churn-v3',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Dataset name',
          type: PropertyType.string,
          required: true,
          example: 'Customer Churn Q2 2026',
        ),
        PropertyDef(
          name: 'size',
          displayName: 'Size (MB)',
          type: PropertyType.integer,
          example: '512',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'format',
          displayName: 'Format',
          type: PropertyType.enum_,
          enumValues: [
            'CSV', 'JSON', 'Parquet', 'Avro',
            'TFRecord', 'Image', 'Text', 'Audio',
          ],
          example: 'Parquet',
        ),
        PropertyDef(
          name: 'splitRatio',
          displayName: 'Split ratio',
          type: PropertyType.string,
          example: '80:20',
        ),
        PropertyDef(
          name: 'labelCount',
          displayName: 'Label count',
          type: PropertyType.integer,
          example: '3',
          boundaryLow: '1',
        ),
        PropertyDef(
          name: 'source',
          displayName: 'Source',
          type: PropertyType.string,
          example: 'production_db_export',
        ),
        PropertyDef(
          name: 'version',
          displayName: 'Version',
          type: PropertyType.string,
          example: '3.0.0',
        ),
      ],
    ),
    'prediction': EntityDef(
      id: 'prediction',
      displayName: 'Prediction',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Prediction ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'pred-a1b2c3d4',
        ),
        PropertyDef(
          name: 'modelId',
          displayName: 'Model ID',
          type: PropertyType.string,
          required: true,
          example: 'model-cls-v1-42',
        ),
        PropertyDef(
          name: 'input',
          displayName: 'Input data',
          type: PropertyType.text,
          required: true,
          example: '{"age": 45, "tenure_months": 24, "late_payments": 1}',
        ),
        PropertyDef(
          name: 'output',
          displayName: 'Prediction output',
          type: PropertyType.text,
          required: true,
          example: '{"predicted_class": "will_churn", "probability": 0.87}',
        ),
        PropertyDef(
          name: 'confidence',
          displayName: 'Confidence',
          type: PropertyType.percent,
          example: '87.3',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'latency',
          displayName: 'Latency (ms)',
          type: PropertyType.integer,
          example: '32',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'timestamp',
          displayName: 'Timestamp',
          type: PropertyType.date,
          example: '2026-06-29T14:30:00Z',
        ),
      ],
    ),
    'trainingJob': EntityDef(
      id: 'trainingJob',
      displayName: 'Training job',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Job ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'job-train-789',
        ),
        PropertyDef(
          name: 'modelId',
          displayName: 'Model ID',
          type: PropertyType.string,
          required: true,
          example: 'model-cls-v1-42',
        ),
        PropertyDef(
          name: 'datasetId',
          displayName: 'Dataset ID',
          type: PropertyType.string,
          required: true,
          example: 'ds-customer-churn-v3',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Job status',
          type: PropertyType.enum_,
          enumValues: ['Pending', 'Training', 'Completed', 'Failed', 'Stopped'],
          example: 'Training',
        ),
        PropertyDef(
          name: 'epochs',
          displayName: 'Epochs',
          type: PropertyType.integer,
          example: '50',
          boundaryLow: '1',
          boundaryHigh: '1000',
        ),
        PropertyDef(
          name: 'learningRate',
          displayName: 'Learning rate',
          type: PropertyType.number,
          example: '0.001',
          boundaryLow: '0.00001',
          boundaryHigh: '1.0',
        ),
        PropertyDef(
          name: 'startedAt',
          displayName: 'Started at',
          type: PropertyType.date,
          example: '2026-06-28T10:00:00Z',
        ),
        PropertyDef(
          name: 'completedAt',
          displayName: 'Completed at',
          type: PropertyType.date,
          example: '2026-06-29T02:00:00Z',
        ),
      ],
    ),
    'endpoint': EntityDef(
      id: 'endpoint',
      displayName: 'Endpoint',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Endpoint ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'ep-churn-prod-1',
        ),
        PropertyDef(
          name: 'modelId',
          displayName: 'Model ID',
          type: PropertyType.string,
          required: true,
          example: 'model-cls-v1-42',
        ),
        PropertyDef(
          name: 'url',
          displayName: 'Endpoint URL',
          type: PropertyType.url,
          required: true,
          example: 'https://api.example.com/v2/models/churn:predict',
          invalidExample: 'http://localhost:8080',
        ),
        PropertyDef(
          name: 'runtime',
          displayName: 'Runtime',
          type: PropertyType.enum_,
          enumValues: [
            'TensorFlow Serving', 'TorchServe', 'ONNX Runtime',
            'Triton Inference Server', 'Custom',
          ],
          example: 'TorchServe',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Endpoint status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Inactive', 'Pending', 'Deployed', 'Failed'],
          example: 'Active',
        ),
        PropertyDef(
          name: 'maxBatchSize',
          displayName: 'Max batch size',
          type: PropertyType.integer,
          example: '32',
          boundaryLow: '1',
        ),
        PropertyDef(
          name: 'timeout',
          displayName: 'Timeout (ms)',
          type: PropertyType.integer,
          example: '5000',
          boundaryLow: '100',
        ),
      ],
    ),
    'feature': EntityDef(
      id: 'feature',
      displayName: 'Feature',
      properties: [
        PropertyDef(
          name: 'name',
          displayName: 'Feature name',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'tenure_months',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Feature type',
          type: PropertyType.enum_,
          required: true,
          enumValues: [
            'Numeric', 'Categorical', 'Text', 'Image',
            'Boolean', 'Date', 'Embedding',
          ],
          example: 'Numeric',
        ),
        PropertyDef(
          name: 'importance',
          displayName: 'Importance',
          type: PropertyType.percent,
          example: '23.5',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'cardinality',
          displayName: 'Cardinality',
          type: PropertyType.integer,
          example: '12',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'distribution',
          displayName: 'Distribution',
          type: PropertyType.string,
          example: 'skewed_right',
        ),
        PropertyDef(
          name: 'nullable',
          displayName: 'Nullable',
          type: PropertyType.boolean,
          example: 'false',
        ),
      ],
    ),
    'metric': EntityDef(
      id: 'metric',
      displayName: 'Metric',
      properties: [
        PropertyDef(
          name: 'name',
          displayName: 'Metric name',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'f1_score',
        ),
        PropertyDef(
          name: 'value',
          displayName: 'Value',
          type: PropertyType.number,
          required: true,
          example: '0.923',
        ),
        PropertyDef(
          name: 'threshold',
          displayName: 'Threshold',
          type: PropertyType.number,
          example: '0.85',
        ),
        PropertyDef(
          name: 'timestamp',
          displayName: 'Timestamp',
          type: PropertyType.date,
          example: '2026-06-29T12:00:00Z',
        ),
        PropertyDef(
          name: 'unit',
          displayName: 'Unit',
          type: PropertyType.string,
          example: 'percentage',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: ['Pass', 'Fail', 'Warning'],
          example: 'Pass',
        ),
      ],
    ),
    'experiment': EntityDef(
      id: 'experiment',
      displayName: 'Experiment',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Experiment ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'exp-hparam-tune-42',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Experiment name',
          type: PropertyType.string,
          required: true,
          example: 'Hyperparameter Tuning Round 4',
        ),
        PropertyDef(
          name: 'modelId',
          displayName: 'Model ID',
          type: PropertyType.string,
          required: true,
          example: 'model-cls-v1-42',
        ),
        PropertyDef(
          name: 'params',
          displayName: 'Hyperparameters',
          type: PropertyType.text,
          example: '{"learning_rate": 0.001, "batch_size": 64, "optimizer": "adam"}',
        ),
        PropertyDef(
          name: 'metrics',
          displayName: 'Result metrics',
          type: PropertyType.text,
          example: '{"accuracy": 0.942, "f1_score": 0.938, "latency_ms": 32}',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: ['Running', 'Completed', 'Failed', 'Stopped'],
          example: 'Completed',
        ),
        PropertyDef(
          name: 'startedAt',
          displayName: 'Started at',
          type: PropertyType.date,
          example: '2026-06-25T08:00:00Z',
        ),
        PropertyDef(
          name: 'tags',
          displayName: 'Tags',
          type: PropertyType.string,
          example: 'hparam-tuning, pytorch, production',
        ),
      ],
    ),
  },
  actions: {
    'train': ActionDef(
      id: 'train',
      displayName: 'Train model',
      verb: 'Train',
      pastTense: 'trained',
      preposition: 'on',
      category: ActionCategory.execution,
      requiredPropertyNames: ['modelId', 'datasetId'],
      optionalPropertyNames: ['epochs', 'learningRate'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'training', condition: 'started'),
        StateTransition(fromState: 'training', toState: 'active', condition: 'completed'),
        StateTransition(fromState: 'training', toState: 'failed', condition: 'error'),
      ],
    ),
    'deploy': ActionDef(
      id: 'deploy',
      displayName: 'Deploy model',
      verb: 'Deploy',
      pastTense: 'deployed',
      preposition: 'to',
      category: ActionCategory.deployment,
      requiredPropertyNames: ['modelId'],
      optionalPropertyNames: ['maxBatchSize', 'timeout'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'deployed', condition: 'success'),
        StateTransition(fromState: 'deployed', toState: 'active', condition: 'undeploy'),
        StateTransition(fromState: 'deployed', toState: 'failed', condition: 'crash'),
      ],
    ),
    'predict': ActionDef(
      id: 'predict',
      displayName: 'Run prediction',
      verb: 'Predict',
      pastTense: 'predicted',
      preposition: 'using',
      category: ActionCategory.execution,
      requiredPropertyNames: ['modelId', 'input'],
      optionalPropertyNames: [],
    ),
    'evaluate': ActionDef(
      id: 'evaluate',
      displayName: 'Evaluate model',
      verb: 'Evaluate',
      pastTense: 'evaluated',
      preposition: 'on',
      category: ActionCategory.analytics,
      requiredPropertyNames: ['modelId'],
      optionalPropertyNames: ['datasetId'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'evaluating', condition: 'started'),
        StateTransition(fromState: 'evaluating', toState: 'active', condition: 'completed'),
        StateTransition(fromState: 'evaluating', toState: 'failed', condition: 'error'),
      ],
    ),
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
    ),
    'view': ActionDef(
      id: 'view',
      displayName: 'View',
      verb: 'View',
      pastTense: 'viewed',
      category: ActionCategory.analytics,
      requiredPropertyNames: [],
    ),
    'delete': ActionDef(
      id: 'delete',
      displayName: 'Delete',
      verb: 'Delete',
      pastTense: 'deleted',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'pending': StateDef(id: 'pending', displayName: 'Pending'),
      'training': StateDef(id: 'training', displayName: 'Training'),
      'deployed': StateDef(id: 'deployed', displayName: 'Deployed'),
      'failed': StateDef(id: 'failed', displayName: 'Failed'),
      'archived': StateDef(id: 'archived', displayName: 'Archived', isTerminal: true),
      'evaluating': StateDef(id: 'evaluating', displayName: 'Evaluating'),
    },
    transitions: [
      StateTransition(fromState: 'pending', toState: 'training', condition: 'started'),
      StateTransition(fromState: 'pending', toState: 'failed', condition: 'error'),
      StateTransition(fromState: 'training', toState: 'active', condition: 'completed'),
      StateTransition(fromState: 'training', toState: 'failed', condition: 'error'),
      StateTransition(fromState: 'active', toState: 'deployed', condition: 'deploy'),
      StateTransition(fromState: 'active', toState: 'inactive', condition: 'deactivate'),
      StateTransition(fromState: 'active', toState: 'archived', condition: 'archive'),
      StateTransition(fromState: 'active', toState: 'evaluating', condition: 'evaluate'),
      StateTransition(fromState: 'inactive', toState: 'active', condition: 'reactivate'),
      StateTransition(fromState: 'deployed', toState: 'active', condition: 'undeploy'),
      StateTransition(fromState: 'deployed', toState: 'failed', condition: 'crash'),
      StateTransition(fromState: 'evaluating', toState: 'active', condition: 'completed'),
      StateTransition(fromState: 'evaluating', toState: 'failed', condition: 'error'),
      StateTransition(fromState: 'failed', toState: 'pending', condition: 'retry'),
    ],
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'model', targetEntity: 'dataset', action: 'train'),
    OntologyRelationship(sourceEntity: 'dataset', targetEntity: 'model', action: 'train'),
    OntologyRelationship(sourceEntity: 'model', targetEntity: 'prediction', action: 'predict'),
    OntologyRelationship(sourceEntity: 'model', targetEntity: 'trainingJob', action: 'train'),
    OntologyRelationship(sourceEntity: 'trainingJob', targetEntity: 'model', action: 'create'),
    OntologyRelationship(sourceEntity: 'trainingJob', targetEntity: 'dataset', action: 'create'),
    OntologyRelationship(sourceEntity: 'model', targetEntity: 'endpoint', action: 'deploy'),
    OntologyRelationship(sourceEntity: 'endpoint', targetEntity: 'model', action: 'deploy'),
    OntologyRelationship(sourceEntity: 'model', targetEntity: 'metric', action: 'evaluate'),
    OntologyRelationship(sourceEntity: 'metric', targetEntity: 'model', action: 'evaluate'),
    OntologyRelationship(sourceEntity: 'model', targetEntity: 'experiment', action: 'create'),
    OntologyRelationship(sourceEntity: 'feature', targetEntity: 'model', action: 'create'),
    OntologyRelationship(sourceEntity: 'metric', targetEntity: 'experiment', action: 'view'),
    OntologyRelationship(sourceEntity: 'feature', targetEntity: 'dataset', action: 'view'),
  ],
);
