import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final bankingDomain = DomainOntology(
  id: 'banking',
  displayName: 'Banking',
  synonyms: [
    'banking', 'finance', 'transaction', 'transfer', 'payment',
    'wallet', 'wire', 'deposit', 'withdraw',
  ],
  entities: {
    'wallet': EntityDef(
      id: 'wallet',
      displayName: 'Wallet',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Wallet ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'wlt_a1b2c3d4',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'balance',
          displayName: 'Balance',
          type: PropertyType.number,
          required: true,
          example: '2500.00',
          invalidExample: '-100.00',
          minValue: 0,
        ),
        PropertyDef(
          name: 'currency',
          displayName: 'Currency',
          type: PropertyType.string,
          required: true,
          example: 'USD',
          invalidExample: 'US',
          minLength: 3,
          maxLength: 3,
        ),
        PropertyDef(
          name: 'ownerId',
          displayName: 'Owner ID',
          type: PropertyType.string,
          required: true,
          example: 'user_abc789',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Wallet status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Inactive', 'Frozen', 'Closed'],
          example: 'Active',
        ),
        PropertyDef(
          name: 'dailyLimit',
          displayName: 'Daily limit',
          type: PropertyType.number,
          example: '5000.00',
          minValue: 0,
        ),
      ],
    ),
    'transfer': EntityDef(
      id: 'transfer',
      displayName: 'Transfer',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Transfer ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'trf_9876_abcd',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'fromAccount',
          displayName: 'From account',
          type: PropertyType.string,
          required: true,
          example: 'ACC-1001-2345',
        ),
        PropertyDef(
          name: 'toAccount',
          displayName: 'To account',
          type: PropertyType.string,
          required: true,
          example: 'ACC-2002-6789',
        ),
        PropertyDef(
          name: 'amount',
          displayName: 'Amount',
          type: PropertyType.number,
          required: true,
          example: '1500.00',
          invalidExample: '-50.00',
          minValue: 0.01,
        ),
        PropertyDef(
          name: 'currency',
          displayName: 'Currency',
          type: PropertyType.string,
          required: true,
          example: 'USD',
          minLength: 3,
          maxLength: 3,
        ),
        PropertyDef(
          name: 'memo',
          displayName: 'Memo',
          type: PropertyType.string,
          example: 'Invoice payment for March',
          maxLength: 500,
        ),
        PropertyDef(
          name: 'scheduledDate',
          displayName: 'Scheduled date',
          type: PropertyType.date,
          example: '2026-07-15T09:00:00Z',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Transfer status',
          type: PropertyType.enum_,
          enumValues: ['Pending', 'Processing', 'Completed', 'Failed', 'Cancelled'],
          example: 'Pending',
        ),
      ],
    ),
    'transaction': EntityDef(
      id: 'transaction',
      displayName: 'Transaction',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Transaction ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'txn_4f8a_2c1b',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Transaction type',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Deposit', 'Withdrawal', 'Transfer', 'Payment', 'Fee', 'Refund'],
          example: 'Deposit',
        ),
        PropertyDef(
          name: 'amount',
          displayName: 'Amount',
          type: PropertyType.number,
          required: true,
          example: '750.00',
          invalidExample: '0',
          minValue: 0.01,
        ),
        PropertyDef(
          name: 'currency',
          displayName: 'Currency',
          type: PropertyType.string,
          required: true,
          example: 'USD',
          minLength: 3,
          maxLength: 3,
        ),
        PropertyDef(
          name: 'timestamp',
          displayName: 'Timestamp',
          type: PropertyType.date,
          required: true,
          example: '2026-06-28T14:32:10Z',
        ),
        PropertyDef(
          name: 'description',
          displayName: 'Description',
          type: PropertyType.string,
          example: 'Monthly salary deposit',
          maxLength: 1000,
        ),
        PropertyDef(
          name: 'referenceId',
          displayName: 'Reference ID',
          type: PropertyType.string,
          example: 'ref_INV_2026_003',
        ),
      ],
    ),
    'balance': EntityDef(
      id: 'balance',
      displayName: 'Balance',
      properties: [
        PropertyDef(
          name: 'available',
          displayName: 'Available balance',
          type: PropertyType.number,
          required: true,
          example: '3200.50',
          minValue: 0,
        ),
        PropertyDef(
          name: 'ledger',
          displayName: 'Ledger balance',
          type: PropertyType.number,
          required: true,
          example: '3500.00',
          minValue: 0,
        ),
        PropertyDef(
          name: 'pending',
          displayName: 'Pending amount',
          type: PropertyType.number,
          example: '299.50',
          minValue: 0,
        ),
        PropertyDef(
          name: 'currency',
          displayName: 'Currency',
          type: PropertyType.string,
          required: true,
          example: 'USD',
          minLength: 3,
          maxLength: 3,
        ),
        PropertyDef(
          name: 'asOf',
          displayName: 'As of date',
          type: PropertyType.date,
          required: true,
          example: '2026-06-29T08:00:00Z',
        ),
      ],
    ),
    'payee': EntityDef(
      id: 'payee',
      displayName: 'Payee',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Payee ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'pay_55e8f1a2',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Payee name',
          type: PropertyType.string,
          required: true,
          example: 'Acme Corp',
          maxLength: 200,
        ),
        PropertyDef(
          name: 'accountNumber',
          displayName: 'Account number',
          type: PropertyType.string,
          required: true,
          isSensitive: true,
          example: '****6789',
          invalidExample: '123',
          pattern: r'^\d{4,20}$',
        ),
        PropertyDef(
          name: 'routingNumber',
          displayName: 'Routing number',
          type: PropertyType.string,
          isSensitive: true,
          example: '****0001',
          invalidExample: '00',
          pattern: r'^\d{9}$',
        ),
        PropertyDef(
          name: 'email',
          displayName: 'Email',
          type: PropertyType.email,
          example: 'payments@acme.com',
          invalidExample: 'not-an-email',
        ),
        PropertyDef(
          name: 'nickname',
          displayName: 'Nickname',
          type: PropertyType.string,
          example: 'Acme invoices',
          maxLength: 100,
        ),
      ],
    ),
    'beneficiary': EntityDef(
      id: 'beneficiary',
      displayName: 'Beneficiary',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Beneficiary ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'ben_3c7d9e1f',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Beneficiary name',
          type: PropertyType.string,
          required: true,
          example: 'Jane Smith',
          maxLength: 200,
        ),
        PropertyDef(
          name: 'accountNumber',
          displayName: 'Account number',
          type: PropertyType.string,
          required: true,
          isSensitive: true,
          example: '****4321',
          invalidExample: '12',
          pattern: r'^\d{4,20}$',
        ),
        PropertyDef(
          name: 'bankName',
          displayName: 'Bank name',
          type: PropertyType.string,
          required: true,
          example: 'Chase Bank',
        ),
        PropertyDef(
          name: 'relationship',
          displayName: 'Relationship',
          type: PropertyType.enum_,
          enumValues: ['Spouse', 'Parent', 'Child', 'Friend', 'Business partner'],
          example: 'Business partner',
        ),
      ],
    ),
    'account': EntityDef(
      id: 'account',
      displayName: 'Account',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Account ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'ACC-1001-2345',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Account type',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Checking', 'Savings', 'Credit', 'Investment', 'Loan'],
          example: 'Checking',
        ),
        PropertyDef(
          name: 'number',
          displayName: 'Account number',
          type: PropertyType.string,
          required: true,
          isSensitive: true,
          example: '****5678',
          pattern: r'^\d{4,20}$',
        ),
        PropertyDef(
          name: 'holderName',
          displayName: 'Holder name',
          type: PropertyType.string,
          required: true,
          example: 'Alice Johnson',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Account status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Inactive', 'Frozen', 'Closed'],
          example: 'Active',
        ),
        PropertyDef(
          name: 'openedAt',
          displayName: 'Opened date',
          type: PropertyType.date,
          required: true,
          example: '2024-01-15T00:00:00Z',
        ),
        PropertyDef(
          name: 'branchCode',
          displayName: 'Branch code',
          type: PropertyType.string,
          example: 'BR-042',
          maxLength: 10,
        ),
      ],
    ),
    'limit': EntityDef(
      id: 'limit',
      displayName: 'Limit',
      properties: [
        PropertyDef(
          name: 'type',
          displayName: 'Limit type',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Daily', 'Weekly', 'Monthly', 'PerTransaction'],
          example: 'Daily',
        ),
        PropertyDef(
          name: 'dailyMax',
          displayName: 'Daily maximum',
          type: PropertyType.number,
          example: '10000.00',
          minValue: 0,
        ),
        PropertyDef(
          name: 'perTransactionMax',
          displayName: 'Per transaction max',
          type: PropertyType.number,
          example: '5000.00',
          minValue: 0,
        ),
        PropertyDef(
          name: 'remaining',
          displayName: 'Remaining',
          type: PropertyType.number,
          example: '4500.00',
          minValue: 0,
        ),
      ],
    ),
    'fee': EntityDef(
      id: 'fee',
      displayName: 'Fee',
      properties: [
        PropertyDef(
          name: 'type',
          displayName: 'Fee type',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Wire', 'Overdraft', 'International', 'Service', 'Late payment'],
          example: 'Wire',
        ),
        PropertyDef(
          name: 'amount',
          displayName: 'Amount',
          type: PropertyType.number,
          example: '25.00',
          minValue: 0,
        ),
        PropertyDef(
          name: 'percentage',
          displayName: 'Percentage',
          type: PropertyType.percent,
          example: '1.5',
          minValue: 0,
          maxValue: 100,
        ),
        PropertyDef(
          name: 'minAmount',
          displayName: 'Minimum amount',
          type: PropertyType.number,
          example: '5.00',
          minValue: 0,
        ),
        PropertyDef(
          name: 'maxAmount',
          displayName: 'Maximum amount',
          type: PropertyType.number,
          example: '100.00',
          minValue: 0,
        ),
      ],
    ),
  },
  actions: {
    'transfer': ActionDef(
      id: 'transfer',
      displayName: 'Transfer funds',
      verb: 'Transfer',
      pastTense: 'transferred',
      preposition: 'from',
      category: ActionCategory.transaction,
      requiredPropertyNames: ['fromAccount', 'toAccount', 'amount', 'currency'],
      optionalPropertyNames: ['memo', 'scheduledDate'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'completed', condition: 'settled'),
        StateTransition(fromState: 'pending', toState: 'failed', condition: 'rejected'),
        StateTransition(fromState: 'pending', toState: 'cancelled', condition: 'user_cancelled'),
        StateTransition(fromState: 'pending', toState: 'insufficient', condition: 'insufficient_funds'),
      ],
    ),
    'deposit': ActionDef(
      id: 'deposit',
      displayName: 'Make deposit',
      verb: 'Deposit',
      pastTense: 'deposited',
      preposition: 'into',
      category: ActionCategory.transaction,
      requiredPropertyNames: ['amount', 'currency'],
      optionalPropertyNames: ['description'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'completed', condition: 'cleared'),
        StateTransition(fromState: 'pending', toState: 'failed', condition: 'declined'),
      ],
    ),
    'withdraw': ActionDef(
      id: 'withdraw',
      displayName: 'Withdraw funds',
      verb: 'Withdraw',
      pastTense: 'withdrew',
      preposition: 'from',
      category: ActionCategory.transaction,
      requiredPropertyNames: ['amount', 'currency'],
      optionalPropertyNames: ['description'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'completed', condition: 'disbursed'),
        StateTransition(fromState: 'pending', toState: 'insufficient', condition: 'insufficient_funds'),
        StateTransition(fromState: 'pending', toState: 'failed', condition: 'error'),
      ],
    ),
    'schedule': ActionDef(
      id: 'schedule',
      displayName: 'Schedule transfer',
      verb: 'Schedule',
      pastTense: 'scheduled',
      category: ActionCategory.scheduling,
      requiredPropertyNames: ['fromAccount', 'toAccount', 'amount', 'scheduledDate'],
      optionalPropertyNames: ['memo'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'processing', condition: 'due'),
        StateTransition(fromState: 'pending', toState: 'cancelled', condition: 'user_cancelled'),
      ],
    ),
    'execute': ActionDef(
      id: 'execute',
      displayName: 'Execute transaction',
      verb: 'Execute',
      pastTense: 'executed',
      category: ActionCategory.execution,
      requiredPropertyNames: ['id'],
      transitions: [
        StateTransition(fromState: 'processing', toState: 'completed', condition: 'success'),
        StateTransition(fromState: 'processing', toState: 'failed', condition: 'failure'),
      ],
    ),
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
    ),
    'view': ActionDef(
      id: 'view',
      displayName: 'View',
      verb: 'View',
      pastTense: 'viewed',
      category: ActionCategory.analytics,
      requiredPropertyNames: [],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'pending': StateDef(id: 'pending', displayName: 'Pending'),
      'processing': StateDef(id: 'processing', displayName: 'Processing'),
      'completed': StateDef(id: 'completed', displayName: 'Completed', isTerminal: true),
      'failed': StateDef(id: 'failed', displayName: 'Failed', isTerminal: true),
      'cancelled': StateDef(id: 'cancelled', displayName: 'Cancelled', isTerminal: true),
      'insufficient': StateDef(id: 'insufficient', displayName: 'Insufficient funds'),
      'frozen': StateDef(id: 'frozen', displayName: 'Frozen'),
      'closed': StateDef(id: 'closed', displayName: 'Closed', isTerminal: true),
    },
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'wallet', targetEntity: 'transaction', action: 'create'),
    OntologyRelationship(sourceEntity: 'wallet', targetEntity: 'balance', action: 'view'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'transfer', action: 'transfer'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'transfer', action: 'schedule'),
    OntologyRelationship(sourceEntity: 'transfer', targetEntity: 'transaction', action: 'execute'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'transaction', action: 'deposit'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'transaction', action: 'withdraw'),
    OntologyRelationship(sourceEntity: 'payee', targetEntity: 'transfer', action: 'transfer'),
    OntologyRelationship(sourceEntity: 'beneficiary', targetEntity: 'transfer', action: 'transfer'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'limit', action: 'view'),
    OntologyRelationship(sourceEntity: 'transaction', targetEntity: 'fee', action: 'create'),
    OntologyRelationship(sourceEntity: 'wallet', targetEntity: 'limit', action: 'view'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'payee', action: 'create'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'beneficiary', action: 'create'),
  ],
);
