import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final commerceDomain = DomainOntology(
  id: 'commerce',
  displayName: 'Commerce',
  synonyms: [
    'ecommerce', 'shop', 'store', 'cart', 'checkout',
    'order', 'product', 'shopping',
  ],
  entities: {
    'cart': EntityDef(
      id: 'cart',
      displayName: 'Cart',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Cart ID',
          type: PropertyType.string,
          isIdentifier: true,
          example: 'cart_abc123',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'itemsCount',
          displayName: 'Items count',
          type: PropertyType.integer,
          example: '3',
          boundaryLow: '0',
          boundaryHigh: '999',
        ),
        PropertyDef(
          name: 'total',
          displayName: 'Total',
          type: PropertyType.number,
          example: '149.99',
          boundaryLow: '0',
          boundaryHigh: '99999.99',
        ),
        PropertyDef(
          name: 'couponCode',
          displayName: 'Coupon code',
          type: PropertyType.string,
          example: 'SAVE20',
          invalidExample: 'INVALID',
        ),
      ],
    ),
    'product': EntityDef(
      id: 'product',
      displayName: 'Product',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Product ID',
          type: PropertyType.string,
          isIdentifier: true,
          example: 'prod_789xyz',
          invalidExample: 'fake_id',
        ),
        PropertyDef(
          name: 'sku',
          displayName: 'SKU',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'SKU-001-ABC',
          invalidExample: ' ',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Product name',
          type: PropertyType.string,
          required: true,
          example: 'Wireless Headphones',
          invalidExample: '',
          minLength: 1,
          maxLength: 200,
        ),
        PropertyDef(
          name: 'price',
          displayName: 'Price',
          type: PropertyType.number,
          required: true,
          example: '79.99',
          boundaryLow: '0.01',
          boundaryHigh: '99999.99',
        ),
        PropertyDef(
          name: 'category',
          displayName: 'Category',
          type: PropertyType.string,
          example: 'Electronics',
        ),
        PropertyDef(
          name: 'stock',
          displayName: 'Stock quantity',
          type: PropertyType.integer,
          example: '150',
          boundaryLow: '0',
          boundaryHigh: '100000',
        ),
        PropertyDef(
          name: 'description',
          displayName: 'Description',
          type: PropertyType.text,
          example: 'High-quality wireless headphones with noise cancellation.',
          maxLength: 5000,
        ),
      ],
    ),
    'order': EntityDef(
      id: 'order',
      displayName: 'Order',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Order ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'ORD-20260629-0042',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Order status',
          type: PropertyType.enum_,
          enumValues: [
            'Pending', 'Processing', 'Shipped',
            'Delivered', 'Cancelled', 'Refunded',
          ],
          example: 'Pending',
        ),
        PropertyDef(
          name: 'total',
          displayName: 'Total',
          type: PropertyType.number,
          required: true,
          example: '249.98',
          boundaryLow: '0',
          boundaryHigh: '99999.99',
        ),
        PropertyDef(
          name: 'items',
          displayName: 'Order items',
          type: PropertyType.text,
          example: '3x Wireless Headphones, 1x USB Cable',
        ),
        PropertyDef(
          name: 'createdAt',
          displayName: 'Created at',
          type: PropertyType.date,
          example: '2026-06-29T10:30:00Z',
        ),
        PropertyDef(
          name: 'shippingAddress',
          displayName: 'Shipping address',
          type: PropertyType.string,
          example: '123 Main St, Springfield, IL 62701',
        ),
        PropertyDef(
          name: 'paymentMethod',
          displayName: 'Payment method',
          type: PropertyType.string,
          example: 'Visa ending in 4242',
        ),
      ],
    ),
    'coupon': EntityDef(
      id: 'coupon',
      displayName: 'Coupon',
      properties: [
        PropertyDef(
          name: 'code',
          displayName: 'Coupon code',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'WELCOME10',
          invalidExample: 'EXPIRED',
        ),
        PropertyDef(
          name: 'discountPercent',
          displayName: 'Discount percentage',
          type: PropertyType.percent,
          example: '20',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'minPurchase',
          displayName: 'Minimum purchase',
          type: PropertyType.number,
          example: '50.00',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'expiresAt',
          displayName: 'Expires at',
          type: PropertyType.date,
          example: '2026-12-31T23:59:59Z',
        ),
        PropertyDef(
          name: 'usageLimit',
          displayName: 'Usage limit',
          type: PropertyType.integer,
          example: '100',
          boundaryLow: '1',
          boundaryHigh: '999999',
        ),
      ],
    ),
    'giftCard': EntityDef(
      id: 'giftCard',
      displayName: 'Gift card',
      properties: [
        PropertyDef(
          name: 'code',
          displayName: 'Gift card code',
          type: PropertyType.code,
          isIdentifier: true,
          required: true,
          example: 'GC-ABCD-1234-EFGH',
          invalidExample: 'INVALID',
        ),
        PropertyDef(
          name: 'balance',
          displayName: 'Balance',
          type: PropertyType.number,
          required: true,
          example: '50.00',
          boundaryLow: '0',
          boundaryHigh: '10000.00',
        ),
        PropertyDef(
          name: 'expiresAt',
          displayName: 'Expires at',
          type: PropertyType.date,
          example: '2027-06-29T23:59:59Z',
        ),
      ],
    ),
    'payment': EntityDef(
      id: 'payment',
      displayName: 'Payment',
      properties: [
        PropertyDef(
          name: 'method',
          displayName: 'Payment method',
          type: PropertyType.string,
          required: true,
          example: 'Credit Card',
        ),
        PropertyDef(
          name: 'cardNumber',
          displayName: 'Card number',
          type: PropertyType.string,
          isSensitive: true,
          example: '4111111111111111',
          invalidExample: '1234',
          pattern: r'^\d{13,19}$',
        ),
        PropertyDef(
          name: 'expiryDate',
          displayName: 'Expiry date',
          type: PropertyType.string,
          example: '12/28',
          invalidExample: '00/00',
        ),
        PropertyDef(
          name: 'cvv',
          displayName: 'CVV',
          type: PropertyType.string,
          isSensitive: true,
          example: '123',
          invalidExample: '12',
          minLength: 3,
          maxLength: 4,
        ),
        PropertyDef(
          name: 'billingAddress',
          displayName: 'Billing address',
          type: PropertyType.string,
          example: '123 Main St, Springfield, IL 62701',
        ),
        PropertyDef(
          name: 'transactionId',
          displayName: 'Transaction ID',
          type: PropertyType.string,
          example: 'txn_abc123def456',
          invalidExample: 'fake_txn',
        ),
      ],
    ),
    'address': EntityDef(
      id: 'address',
      displayName: 'Address',
      properties: [
        PropertyDef(
          name: 'street',
          displayName: 'Street address',
          type: PropertyType.string,
          required: true,
          example: '125 Innovation Drive',
          invalidExample: '',
          minLength: 5,
          maxLength: 200,
        ),
        PropertyDef(
          name: 'city',
          displayName: 'City',
          type: PropertyType.string,
          required: true,
          example: 'San Francisco',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'state',
          displayName: 'State',
          type: PropertyType.string,
          example: 'CA',
        ),
        PropertyDef(
          name: 'zip',
          displayName: 'ZIP code',
          type: PropertyType.string,
          example: '94105',
          invalidExample: 'abc',
        ),
        PropertyDef(
          name: 'country',
          displayName: 'Country',
          type: PropertyType.string,
          example: 'United States',
        ),
        PropertyDef(
          name: 'label',
          displayName: 'Address label',
          type: PropertyType.string,
          example: 'Home',
        ),
      ],
    ),
    'shipping': EntityDef(
      id: 'shipping',
      displayName: 'Shipping',
      properties: [
        PropertyDef(
          name: 'method',
          displayName: 'Shipping method',
          type: PropertyType.string,
          example: 'Express',
        ),
        PropertyDef(
          name: 'trackingNumber',
          displayName: 'Tracking number',
          type: PropertyType.string,
          example: '1Z999AA10123456784',
          invalidExample: '0',
        ),
        PropertyDef(
          name: 'carrier',
          displayName: 'Carrier',
          type: PropertyType.string,
          example: 'UPS',
        ),
        PropertyDef(
          name: 'estimatedDays',
          displayName: 'Estimated days',
          type: PropertyType.integer,
          example: '3',
          boundaryLow: '1',
          boundaryHigh: '60',
        ),
        PropertyDef(
          name: 'cost',
          displayName: 'Shipping cost',
          type: PropertyType.number,
          example: '12.99',
          boundaryLow: '0',
          boundaryHigh: '999.99',
        ),
      ],
    ),
    'receipt': EntityDef(
      id: 'receipt',
      displayName: 'Receipt',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Receipt ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'RCT-20260629-8821',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'items',
          displayName: 'Receipt items',
          type: PropertyType.text,
          example: 'Wireless Headphones x1 - 79.99, USB Cable x2 - 15.98',
        ),
        PropertyDef(
          name: 'subtotal',
          displayName: 'Subtotal',
          type: PropertyType.number,
          example: '95.97',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'tax',
          displayName: 'Tax',
          type: PropertyType.number,
          example: '8.64',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'total',
          displayName: 'Total',
          type: PropertyType.number,
          required: true,
          example: '104.61',
          boundaryLow: '0',
          boundaryHigh: '99999.99',
        ),
        PropertyDef(
          name: 'date',
          displayName: 'Receipt date',
          type: PropertyType.date,
          example: '2026-06-29T10:35:00Z',
        ),
      ],
    ),
    'inventory': EntityDef(
      id: 'inventory',
      displayName: 'Inventory',
      properties: [
        PropertyDef(
          name: 'sku',
          displayName: 'SKU',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'SKU-001-ABC',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'quantity',
          displayName: 'Quantity on hand',
          type: PropertyType.integer,
          required: true,
          example: '250',
          boundaryLow: '0',
          boundaryHigh: '999999',
        ),
        PropertyDef(
          name: 'warehouse',
          displayName: 'Warehouse',
          type: PropertyType.string,
          example: 'WH-CHI-01',
        ),
        PropertyDef(
          name: 'reorderPoint',
          displayName: 'Reorder point',
          type: PropertyType.integer,
          example: '50',
          boundaryLow: '0',
        ),
      ],
    ),
  },
  actions: {
    'add': ActionDef(
      id: 'add',
      displayName: 'Add to cart',
      verb: 'Add',
      pastTense: 'added',
      preposition: 'to',
      category: ActionCategory.commerce,
      requiredPropertyNames: ['itemsCount'],
      optionalPropertyNames: ['couponCode'],
      transitions: [
        StateTransition(fromState: 'inactive', toState: 'active', condition: 'first item'),
        StateTransition(fromState: 'active', toState: 'active', condition: 'additional item'),
      ],
    ),
    'remove': ActionDef(
      id: 'remove',
      displayName: 'Remove from cart',
      verb: 'Remove',
      pastTense: 'removed',
      preposition: 'from',
      category: ActionCategory.commerce,
      requiredPropertyNames: [],
      optionalPropertyNames: ['id'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'inactive', condition: 'last item'),
        StateTransition(fromState: 'active', toState: 'active', condition: 'remaining items'),
      ],
    ),
    'updateQuantity': ActionDef(
      id: 'updateQuantity',
      displayName: 'Update quantity',
      verb: 'Update',
      pastTense: 'updated',
      preposition: 'to',
      category: ActionCategory.commerce,
      requiredPropertyNames: ['itemsCount'],
      optionalPropertyNames: ['id'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'active', condition: 'changed'),
      ],
    ),
    'checkout': ActionDef(
      id: 'checkout',
      displayName: 'Checkout',
      verb: 'Checkout',
      pastTense: 'checked out',
      category: ActionCategory.commerce,
      requiredPropertyNames: ['itemsCount', 'total'],
      optionalPropertyNames: ['couponCode', 'shippingAddress'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'pending', condition: 'order created'),
        StateTransition(fromState: 'active', toState: 'cancelled', condition: 'abandoned'),
      ],
    ),
    'pay': ActionDef(
      id: 'pay',
      displayName: 'Pay',
      verb: 'Pay',
      pastTense: 'paid',
      preposition: 'via',
      category: ActionCategory.transaction,
      requiredPropertyNames: ['method', 'total'],
      optionalPropertyNames: ['cardNumber', 'expiryDate', 'cvv', 'billingAddress', 'transactionId'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'processing', condition: 'payment authorized'),
        StateTransition(fromState: 'pending', toState: 'failed', condition: 'payment declined'),
      ],
    ),
    'apply': ActionDef(
      id: 'apply',
      displayName: 'Apply coupon',
      verb: 'Apply',
      pastTense: 'applied',
      preposition: 'to',
      category: ActionCategory.commerce,
      requiredPropertyNames: ['couponCode', 'code'],
      optionalPropertyNames: ['discountPercent'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'active', condition: 'coupon valid'),
        StateTransition(fromState: 'active', toState: 'failed', condition: 'coupon expired'),
      ],
    ),
    'redeem': ActionDef(
      id: 'redeem',
      displayName: 'Redeem gift card',
      verb: 'Redeem',
      pastTense: 'redeemed',
      preposition: 'on',
      category: ActionCategory.commerce,
      requiredPropertyNames: ['code', 'balance'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'active', condition: 'balance applied'),
        StateTransition(fromState: 'active', toState: 'expired', condition: 'card expired'),
      ],
    ),
    'confirm': ActionDef(
      id: 'confirm',
      displayName: 'Confirm order',
      verb: 'Confirm',
      pastTense: 'confirmed',
      category: ActionCategory.commerce,
      requiredPropertyNames: ['id', 'status', 'total'],
      optionalPropertyNames: ['shippingAddress', 'paymentMethod'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'processing', condition: 'confirmed'),
        StateTransition(fromState: 'processing', toState: 'shipped', condition: 'dispatched'),
        StateTransition(fromState: 'shipped', toState: 'delivered', condition: 'received'),
      ],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'pending': StateDef(id: 'pending', displayName: 'Pending'),
      'processing': StateDef(id: 'processing', displayName: 'Processing'),
      'shipped': StateDef(id: 'shipped', displayName: 'Shipped'),
      'delivered': StateDef(id: 'delivered', displayName: 'Delivered', isTerminal: true),
      'cancelled': StateDef(id: 'cancelled', displayName: 'Cancelled', isTerminal: true),
      'refunded': StateDef(id: 'refunded', displayName: 'Refunded', isTerminal: true),
      'expired': StateDef(id: 'expired', displayName: 'Expired', isTerminal: true),
      'failed': StateDef(id: 'failed', displayName: 'Failed'),
    },
    transitions: [
      StateTransition(fromState: 'active', toState: 'inactive', condition: 'emptied'),
      StateTransition(fromState: 'inactive', toState: 'active', condition: 'item added'),
      StateTransition(fromState: 'pending', toState: 'processing', condition: 'payment confirmed'),
      StateTransition(fromState: 'pending', toState: 'cancelled', condition: 'user cancelled'),
      StateTransition(fromState: 'processing', toState: 'shipped', condition: 'dispatched'),
      StateTransition(fromState: 'processing', toState: 'cancelled', condition: 'vendor cancelled'),
      StateTransition(fromState: 'shipped', toState: 'delivered', condition: 'received'),
      StateTransition(fromState: 'delivered', toState: 'refunded', condition: 'returned'),
      StateTransition(fromState: 'cancelled', toState: 'refunded', condition: 'refund issued'),
      StateTransition(fromState: 'active', toState: 'expired', condition: 'session timeout'),
      StateTransition(fromState: 'pending', toState: 'failed', condition: 'payment declined'),
    ],
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'cart', targetEntity: 'product', action: 'add'),
    OntologyRelationship(sourceEntity: 'product', targetEntity: 'cart', action: 'add'),
    OntologyRelationship(sourceEntity: 'cart', targetEntity: 'cart', action: 'remove'),
    OntologyRelationship(sourceEntity: 'cart', targetEntity: 'cart', action: 'updateQuantity'),
    OntologyRelationship(sourceEntity: 'cart', targetEntity: 'order', action: 'checkout'),
    OntologyRelationship(sourceEntity: 'address', targetEntity: 'order', action: 'checkout'),
    OntologyRelationship(sourceEntity: 'order', targetEntity: 'payment', action: 'pay'),
    OntologyRelationship(sourceEntity: 'payment', targetEntity: 'order', action: 'pay'),
    OntologyRelationship(sourceEntity: 'coupon', targetEntity: 'cart', action: 'apply'),
    OntologyRelationship(sourceEntity: 'giftCard', targetEntity: 'cart', action: 'redeem'),
    OntologyRelationship(sourceEntity: 'order', targetEntity: 'order', action: 'confirm'),
    OntologyRelationship(sourceEntity: 'shipping', targetEntity: 'order', action: 'confirm'),
    OntologyRelationship(sourceEntity: 'receipt', targetEntity: 'order', action: 'confirm'),
    OntologyRelationship(sourceEntity: 'inventory', targetEntity: 'product', action: 'add'),
  ],
);
