import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final identityDomain = DomainOntology(
  id: 'identity',
  displayName: 'Identity',
  synonyms: [
    'login', 'signin', 'sign in', 'auth', 'authenticate',
    'password', 'session', 'token', 'mfa', 'otp',
    'logout', 'oauth', 'sso', 'single sign on',
  ],
  entities: {
    'account': EntityDef(
      id: 'account',
      displayName: 'Account',
      properties: [
        PropertyDef(
          name: 'email',
          displayName: 'Email address',
          type: PropertyType.email,
          required: true,
          isIdentifier: true,
          example: 'alice@example.com',
          invalidExample: 'not-an-email',
          pattern: r'^[^@]+@[^@]+\.[^@]+$',
        ),
        PropertyDef(
          name: 'displayName',
          displayName: 'Display name',
          type: PropertyType.string,
          example: 'Alice Johnson',
          minLength: 2,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Account status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Inactive', 'Locked', 'Pending'],
          example: 'Active',
        ),
      ],
    ),
    'credential': EntityDef(
      id: 'credential',
      displayName: 'Credential',
      properties: [
        PropertyDef(
          name: 'password',
          displayName: 'Password',
          type: PropertyType.password,
          required: true,
          isSensitive: true,
          minLength: 8,
          maxLength: 128,
          example: 'P@ssw0rd!',
          invalidExample: 'short',
          hint: '8+ characters with uppercase, number, and special char',
        ),
        PropertyDef(
          name: 'currentPassword',
          displayName: 'Current password',
          type: PropertyType.password,
          isSensitive: true,
          example: 'OldP@ss123',
        ),
        PropertyDef(
          name: 'newPassword',
          displayName: 'New password',
          type: PropertyType.password,
          isSensitive: true,
          example: 'NewP@ss456',
        ),
      ],
    ),
    'session': EntityDef(
      id: 'session',
      displayName: 'Session',
      properties: [
        PropertyDef(
          name: 'sessionToken',
          displayName: 'Session token',
          type: PropertyType.token,
          isSensitive: true,
          example: 'sess_abc123_def456',
          invalidExample: 'tampered_token_xyz',
        ),
        PropertyDef(
          name: 'expiresAt',
          displayName: 'Expiration',
          type: PropertyType.date,
          example: '2026-07-01T23:59:59Z',
        ),
        PropertyDef(
          name: 'deviceId',
          displayName: 'Device ID',
          type: PropertyType.string,
          example: 'device-abc-7724',
        ),
      ],
    ),
    'token': EntityDef(
      id: 'token',
      displayName: 'Token',
      properties: [
        PropertyDef(
          name: 'accessToken',
          displayName: 'Access token',
          type: PropertyType.token,
          isSensitive: true,
          example: 'eyJhbGciOiJIUzI1NiJ9.valid_token',
          invalidExample: 'eyJhbGciOiJub25lIn0.forged_token',
        ),
        PropertyDef(
          name: 'refreshToken',
          displayName: 'Refresh token',
          type: PropertyType.token,
          isSensitive: true,
          example: 'rt_valid_abc123',
          invalidExample: 'rt_expired_xyz789',
        ),
        PropertyDef(
          name: 'scope',
          displayName: 'Scope',
          type: PropertyType.string,
          example: 'email profile openid',
        ),
        PropertyDef(
          name: 'expiresIn',
          displayName: 'Expires in (seconds)',
          type: PropertyType.integer,
          example: '3600',
          boundaryLow: '0',
          boundaryHigh: '86400',
        ),
      ],
    ),
    'oauthProvider': EntityDef(
      id: 'oauthProvider',
      displayName: 'OAuth provider',
      properties: [
        PropertyDef(
          name: 'provider',
          displayName: 'Provider',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Google', 'Facebook', 'Apple', 'GitHub'],
          example: 'Google',
        ),
        PropertyDef(
          name: 'clientId',
          displayName: 'Client ID',
          type: PropertyType.string,
          isSensitive: true,
          example: '1234567890-apps.googleusercontent.com',
        ),
        PropertyDef(
          name: 'redirectUri',
          displayName: 'Redirect URI',
          type: PropertyType.url,
          required: true,
          example: 'https://app.example.com/oauth/callback',
          invalidExample: 'https://evil.com/callback',
          boundaryHigh: 'https://app.example.com/' + ('a' * 2000),
        ),
        PropertyDef(
          name: 'scope',
          displayName: 'Scope',
          type: PropertyType.string,
          example: 'email profile openid',
        ),
        PropertyDef(
          name: 'state',
          displayName: 'State parameter',
          type: PropertyType.token,
          required: true,
          example: 'csrf_state_a1b2c3d4',
          invalidExample: 'attacker_state_xyz',
        ),
        PropertyDef(
          name: 'authCode',
          displayName: 'Authorization code',
          type: PropertyType.code,
          example: 'AUTH_CODE_abc123',
          invalidExample: 'EXPIRED_CODE_xyz789',
        ),
        PropertyDef(
          name: 'grantType',
          displayName: 'Grant type',
          type: PropertyType.enum_,
          enumValues: ['authorization_code', 'refresh_token', 'client_credentials'],
          example: 'authorization_code',
        ),
      ],
    ),
    'otp': EntityDef(
      id: 'otp',
      displayName: 'OTP',
      properties: [
        PropertyDef(
          name: 'code',
          displayName: 'Verification code',
          type: PropertyType.code,
          required: true,
          example: '482916',
          invalidExample: '000000',
          pattern: r'^\d{6}$',
        ),
        PropertyDef(
          name: 'deliveryMethod',
          displayName: 'Delivery method',
          type: PropertyType.enum_,
          enumValues: ['SMS', 'Email', 'Authenticator app'],
          example: 'SMS',
        ),
      ],
    ),
    'loginAttempt': EntityDef(
      id: 'loginAttempt',
      displayName: 'Login attempt',
      properties: [
        PropertyDef(
          name: 'attemptCount',
          displayName: 'Failed attempts',
          type: PropertyType.integer,
          example: '3',
          boundaryHigh: '5',
        ),
        PropertyDef(
          name: 'lockoutDuration',
          displayName: 'Lockout duration',
          type: PropertyType.string,
          example: '15 minutes',
        ),
      ],
    ),
    'resetToken': EntityDef(
      id: 'resetToken',
      displayName: 'Reset token',
      properties: [
        PropertyDef(
          name: 'token',
          displayName: 'Reset token',
          type: PropertyType.token,
          isSensitive: true,
          example: 'reset_token_valid_abc',
          invalidExample: 'reset_token_expired_xyz',
        ),
        PropertyDef(
          name: 'newPassword',
          displayName: 'New password',
          type: PropertyType.password,
          isSensitive: true,
          example: 'NewP@ss789',
        ),
      ],
    ),
  },
  actions: {
    'authenticate': ActionDef(
      id: 'authenticate',
      displayName: 'Authenticate',
      verb: 'Sign in',
      pastTense: 'authenticated',
      preposition: 'with',
      category: ActionCategory.auth,
      requiredPropertyNames: ['email'],
      optionalPropertyNames: ['password'],
      transitions: [
        StateTransition(fromState: 'unauthenticated', toState: 'authenticated', condition: 'valid'),
        StateTransition(fromState: 'unauthenticated', toState: 'unauthenticated', condition: 'invalid'),
      ],
    ),
    'login': ActionDef(
      id: 'login',
      displayName: 'Login',
      verb: 'Log in',
      pastTense: 'logged in',
      preposition: 'to',
      category: ActionCategory.auth,
      requiredPropertyNames: ['email'],
      transitions: [
        StateTransition(fromState: 'inactive', toState: 'active', condition: 'valid'),
        StateTransition(fromState: 'locked', toState: 'failed', condition: 'locked'),
      ],
    ),
    'logout': ActionDef(
      id: 'logout',
      displayName: 'Logout',
      verb: 'Log out',
      pastTense: 'logged out',
      category: ActionCategory.auth,
      requiredPropertyNames: [],
    ),
    'authorize': ActionDef(
      id: 'authorize',
      displayName: 'Authorize',
      verb: 'Authorize',
      pastTense: 'authorized',
      preposition: 'via',
      category: ActionCategory.auth,
      requiredPropertyNames: ['provider', 'redirectUri'],
      optionalPropertyNames: ['scope', 'state', 'authCode'],
    ),
    'refresh': ActionDef(
      id: 'refresh',
      displayName: 'Refresh session',
      verb: 'Refresh',
      pastTense: 'refreshed',
      category: ActionCategory.auth,
      requiredPropertyNames: ['refreshToken'],
    ),
    'reset': ActionDef(
      id: 'reset',
      displayName: 'Reset password',
      verb: 'Reset',
      pastTense: 'reset',
      preposition: 'for',
      category: ActionCategory.auth,
      requiredPropertyNames: ['email'],
      optionalPropertyNames: ['token', 'newPassword'],
    ),
    'verify': ActionDef(
      id: 'verify',
      displayName: 'Verify OTP',
      verb: 'Verify',
      pastTense: 'verified',
      preposition: 'with',
      category: ActionCategory.auth,
      requiredPropertyNames: ['code'],
    ),
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'locked': StateDef(id: 'locked', displayName: 'Locked'),
      'authenticated': StateDef(id: 'authenticated', displayName: 'Authenticated', isTerminal: true),
      'unauthenticated': StateDef(id: 'unauthenticated', displayName: 'Unauthenticated'),
      'authorized': StateDef(id: 'authorized', displayName: 'Authorized', isTerminal: true),
      'expired': StateDef(id: 'expired', displayName: 'Expired'),
      'failed': StateDef(id: 'failed', displayName: 'Failed'),
      'valid': StateDef(id: 'valid', displayName: 'Valid'),
      'invalid': StateDef(id: 'invalid', displayName: 'Invalid'),
    },
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'credential', action: 'authenticate'),
    OntologyRelationship(sourceEntity: 'credential', targetEntity: 'account', action: 'authenticate'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'session', action: 'login'),
    OntologyRelationship(sourceEntity: 'session', targetEntity: 'session', action: 'refresh'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'token', action: 'refresh'),
    OntologyRelationship(sourceEntity: 'token', targetEntity: 'account', action: 'authenticate'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'oauthProvider', action: 'authorize'),
    OntologyRelationship(sourceEntity: 'oauthProvider', targetEntity: 'account', action: 'authorize'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'otp', action: 'verify'),
    OntologyRelationship(sourceEntity: 'otp', targetEntity: 'account', action: 'verify'),
    OntologyRelationship(sourceEntity: 'credential', targetEntity: 'otp', action: 'verify'),
    OntologyRelationship(sourceEntity: 'account', targetEntity: 'credential', action: 'reset'),
    OntologyRelationship(sourceEntity: 'resetToken', targetEntity: 'credential', action: 'reset'),
    OntologyRelationship(sourceEntity: 'loginAttempt', targetEntity: 'account', action: 'create'),
  ],
);
