import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final integrationDomain = DomainOntology(
  id: 'integration',
  displayName: 'Integration',
  synonyms: [
    'integration', 'api', 'webhook', 'endpoint', 'event',
    'callback', 'web service', 'microservice',
  ],
  entities: {
    'webhook': EntityDef(
      id: 'webhook',
      displayName: 'Webhook',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Webhook ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'wh_abc123def456',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'url',
          displayName: 'Callback URL',
          type: PropertyType.url,
          required: true,
          example: 'https://api.example.com/webhooks/callback',
          invalidExample: 'ftp://bad-url',
        ),
        PropertyDef(
          name: 'secret',
          displayName: 'Signing secret',
          type: PropertyType.token,
          isSensitive: true,
          example: 'whsec_abc123def456',
          invalidExample: 'weak_secret',
        ),
        PropertyDef(
          name: 'events',
          displayName: 'Subscribed events',
          type: PropertyType.string,
          example: 'order.created,payment.completed',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Webhook status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Inactive', 'Failed'],
          example: 'Active',
        ),
        PropertyDef(
          name: 'createdAt',
          displayName: 'Created at',
          type: PropertyType.date,
          example: '2026-06-29T08:00:00Z',
        ),
        PropertyDef(
          name: 'retryCount',
          displayName: 'Retry count',
          type: PropertyType.integer,
          example: '3',
          boundaryLow: '0',
          boundaryHigh: '10',
        ),
      ],
    ),
    'apiKey': EntityDef(
      id: 'apiKey',
      displayName: 'API key',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Key ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'key_live_abc123',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'key',
          displayName: 'API key value',
          type: PropertyType.token,
          isSensitive: true,
          required: true,
          example: 'sk_live_4eC39HqLyjWDarjtT1zdp7dc',
          invalidExample: 'sk_test_short',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Key name',
          type: PropertyType.string,
          example: 'Production API Key',
          minLength: 1,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'permissions',
          displayName: 'Permissions',
          type: PropertyType.string,
          example: 'read:orders,write:products',
        ),
        PropertyDef(
          name: 'expiresAt',
          displayName: 'Expires at',
          type: PropertyType.date,
          example: '2027-06-29T23:59:59Z',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Key status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Inactive', 'Expired'],
          example: 'Active',
        ),
      ],
    ),
    'endpoint': EntityDef(
      id: 'endpoint',
      displayName: 'Endpoint',
      properties: [
        PropertyDef(
          name: 'path',
          displayName: 'Path',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: '/api/v2/orders',
          invalidExample: 'no-slash',
        ),
        PropertyDef(
          name: 'method',
          displayName: 'HTTP method',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
          example: 'POST',
        ),
        PropertyDef(
          name: 'description',
          displayName: 'Description',
          type: PropertyType.text,
          example: 'Creates a new order in the system',
          maxLength: 2000,
        ),
        PropertyDef(
          name: 'authRequired',
          displayName: 'Auth required',
          type: PropertyType.boolean,
          example: 'true',
        ),
        PropertyDef(
          name: 'rateLimit',
          displayName: 'Rate limit (req/s)',
          type: PropertyType.integer,
          example: '100',
          boundaryLow: '1',
          boundaryHigh: '10000',
        ),
        PropertyDef(
          name: 'timeout',
          displayName: 'Timeout (ms)',
          type: PropertyType.integer,
          example: '30000',
          boundaryLow: '100',
          boundaryHigh: '60000',
        ),
      ],
    ),
    'request': EntityDef(
      id: 'request',
      displayName: 'Request',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Request ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'req_abc123xyz',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'method',
          displayName: 'HTTP method',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
          example: 'POST',
        ),
        PropertyDef(
          name: 'url',
          displayName: 'Request URL',
          type: PropertyType.url,
          required: true,
          example: 'https://api.example.com/v2/orders',
          invalidExample: 'not-a-url',
        ),
        PropertyDef(
          name: 'headers',
          displayName: 'Headers',
          type: PropertyType.text,
          example: 'Content-Type: application/json\nAuthorization: Bearer sk_live_xxx',
        ),
        PropertyDef(
          name: 'body',
          displayName: 'Request body',
          type: PropertyType.text,
          example: '{"orderId": "ORD-001", "amount": 49.99}',
        ),
        PropertyDef(
          name: 'timestamp',
          displayName: 'Timestamp',
          type: PropertyType.date,
          example: '2026-06-29T10:00:00Z',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Request status',
          type: PropertyType.enum_,
          enumValues: ['Pending', 'Sent', 'Failed'],
          example: 'Sent',
        ),
      ],
    ),
    'response': EntityDef(
      id: 'response',
      displayName: 'Response',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Response ID',
          type: PropertyType.string,
          isIdentifier: true,
          example: 'res_xyz789abc',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'statusCode',
          displayName: 'Status code',
          type: PropertyType.integer,
          required: true,
          example: '200',
          boundaryLow: '100',
          boundaryHigh: '599',
        ),
        PropertyDef(
          name: 'body',
          displayName: 'Response body',
          type: PropertyType.text,
          example: '{"id": "ORD-001", "status": "created"}',
        ),
        PropertyDef(
          name: 'headers',
          displayName: 'Response headers',
          type: PropertyType.text,
          example: 'Content-Type: application/json\nX-Request-Id: abc123',
        ),
        PropertyDef(
          name: 'latency',
          displayName: 'Latency (ms)',
          type: PropertyType.integer,
          example: '245',
          boundaryLow: '0',
          boundaryHigh: '60000',
        ),
        PropertyDef(
          name: 'timestamp',
          displayName: 'Timestamp',
          type: PropertyType.date,
          example: '2026-06-29T10:00:01Z',
        ),
      ],
    ),
    'event': EntityDef(
      id: 'event',
      displayName: 'Event',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Event ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'evt_abc123def',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Event type',
          type: PropertyType.string,
          required: true,
          example: 'order.created',
          invalidExample: 'unknown',
        ),
        PropertyDef(
          name: 'source',
          displayName: 'Event source',
          type: PropertyType.string,
          required: true,
          example: 'orders-service',
        ),
        PropertyDef(
          name: 'data',
          displayName: 'Event payload',
          type: PropertyType.text,
          example: '{"orderId": "ORD-001", "amount": 49.99}',
        ),
        PropertyDef(
          name: 'timestamp',
          displayName: 'Timestamp',
          type: PropertyType.date,
          example: '2026-06-29T10:00:00Z',
        ),
        PropertyDef(
          name: 'processed',
          displayName: 'Processed',
          type: PropertyType.boolean,
          example: 'false',
        ),
      ],
    ),
    'rateLimit': EntityDef(
      id: 'rateLimit',
      displayName: 'Rate limit',
      properties: [
        PropertyDef(
          name: 'maxRequests',
          displayName: 'Max requests',
          type: PropertyType.integer,
          required: true,
          example: '1000',
          boundaryLow: '1',
          boundaryHigh: '100000',
        ),
        PropertyDef(
          name: 'windowSeconds',
          displayName: 'Window (seconds)',
          type: PropertyType.integer,
          required: true,
          example: '3600',
          boundaryLow: '1',
          boundaryHigh: '86400',
        ),
        PropertyDef(
          name: 'remaining',
          displayName: 'Remaining requests',
          type: PropertyType.integer,
          example: '750',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'resetAt',
          displayName: 'Resets at',
          type: PropertyType.date,
          example: '2026-06-29T11:00:00Z',
        ),
      ],
    ),
    'schema': EntityDef(
      id: 'schema',
      displayName: 'Schema',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Schema ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'sch_order_v2',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Schema name',
          type: PropertyType.string,
          required: true,
          example: 'Order',
          minLength: 1,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'version',
          displayName: 'Version',
          type: PropertyType.string,
          required: true,
          example: 'v2',
          pattern: r'^v\d+$',
        ),
        PropertyDef(
          name: 'fields',
          displayName: 'Fields',
          type: PropertyType.text,
          example: 'id (string), amount (number), status (string)',
        ),
        PropertyDef(
          name: 'required',
          displayName: 'Required fields',
          type: PropertyType.string,
          example: 'id, amount',
        ),
        PropertyDef(
          name: 'description',
          displayName: 'Description',
          type: PropertyType.text,
          example: 'Schema representing a customer order',
          maxLength: 2000,
        ),
      ],
    ),
  },
  actions: {
    'send': ActionDef(
      id: 'send',
      displayName: 'Send request',
      verb: 'Send',
      pastTense: 'sent',
      preposition: 'to',
      category: ActionCategory.communication,
      requiredPropertyNames: ['method', 'url'],
      optionalPropertyNames: ['headers', 'body'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'completed', condition: 'sent'),
        StateTransition(fromState: 'pending', toState: 'failed', condition: 'network error'),
      ],
    ),
    'receive': ActionDef(
      id: 'receive',
      displayName: 'Receive response',
      verb: 'Receive',
      pastTense: 'received',
      preposition: 'from',
      category: ActionCategory.communication,
      requiredPropertyNames: ['statusCode'],
      optionalPropertyNames: ['body', 'headers', 'latency'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'completed', condition: 'success'),
        StateTransition(fromState: 'pending', toState: 'failed', condition: 'timeout'),
      ],
    ),
    'trigger': ActionDef(
      id: 'trigger',
      displayName: 'Trigger event',
      verb: 'Trigger',
      pastTense: 'triggered',
      preposition: 'via',
      category: ActionCategory.execution,
      requiredPropertyNames: ['type', 'source'],
      optionalPropertyNames: ['data'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'pending', condition: 'event fired'),
        StateTransition(fromState: 'pending', toState: 'completed', condition: 'delivered'),
        StateTransition(fromState: 'pending', toState: 'failed', condition: 'delivery failed'),
      ],
    ),
    'call': ActionDef(
      id: 'call',
      displayName: 'Call endpoint',
      verb: 'Call',
      pastTense: 'called',
      preposition: 'on',
      category: ActionCategory.execution,
      requiredPropertyNames: ['path', 'method'],
      optionalPropertyNames: ['authRequired', 'timeout'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'pending', condition: 'request sent'),
        StateTransition(fromState: 'pending', toState: 'completed', condition: 'response received'),
        StateTransition(fromState: 'pending', toState: 'rate_limited', condition: 'throttled'),
      ],
    ),
    'deliver': ActionDef(
      id: 'deliver',
      displayName: 'Deliver payload',
      verb: 'Deliver',
      pastTense: 'delivered',
      preposition: 'to',
      category: ActionCategory.communication,
      requiredPropertyNames: ['url'],
      optionalPropertyNames: ['secret', 'retryCount'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'completed', condition: 'delivered'),
        StateTransition(fromState: 'pending', toState: 'failed', condition: 'delivery failed'),
      ],
    ),
    'retryOp': ActionDef(
      id: 'retryOp',
      displayName: 'Retry operation',
      verb: 'Retry',
      pastTense: 'retried',
      preposition: 'after',
      category: ActionCategory.execution,
      requiredPropertyNames: ['retryCount'],
      optionalPropertyNames: ['url'],
      transitions: [
        StateTransition(fromState: 'retrying', toState: 'retrying', condition: 'retry scheduled'),
        StateTransition(fromState: 'retrying', toState: 'completed', condition: 'success'),
        StateTransition(fromState: 'retrying', toState: 'failed', condition: 'exhausted'),
      ],
    ),
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
      optionalPropertyNames: ['name', 'version'],
      transitions: [
        StateTransition(fromState: 'inactive', toState: 'active', condition: 'created'),
      ],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'pending': StateDef(id: 'pending', displayName: 'Pending'),
      'completed': StateDef(id: 'completed', displayName: 'Completed', isTerminal: true),
      'failed': StateDef(id: 'failed', displayName: 'Failed'),
      'retrying': StateDef(id: 'retrying', displayName: 'Retrying'),
      'rate_limited': StateDef(id: 'rate_limited', displayName: 'Rate limited'),
      'expired': StateDef(id: 'expired', displayName: 'Expired', isTerminal: true),
    },
    transitions: [
      StateTransition(fromState: 'active', toState: 'inactive', condition: 'deactivated'),
      StateTransition(fromState: 'inactive', toState: 'active', condition: 'activated'),
      StateTransition(fromState: 'active', toState: 'pending', condition: 'request initiated'),
      StateTransition(fromState: 'pending', toState: 'completed', condition: 'success'),
      StateTransition(fromState: 'pending', toState: 'failed', condition: 'error'),
      StateTransition(fromState: 'failed', toState: 'retrying', condition: 'automatic retry'),
      StateTransition(fromState: 'retrying', toState: 'completed', condition: 'retry succeeded'),
      StateTransition(fromState: 'retrying', toState: 'failed', condition: 'retries exhausted'),
      StateTransition(fromState: 'active', toState: 'rate_limited', condition: 'throttled'),
      StateTransition(fromState: 'rate_limited', toState: 'active', condition: 'window reset'),
      StateTransition(fromState: 'active', toState: 'expired', condition: 'ttl elapsed'),
      StateTransition(fromState: 'pending', toState: 'rate_limited', condition: 'rate limit hit'),
    ],
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'webhook', targetEntity: 'endpoint', action: 'trigger'),
    OntologyRelationship(sourceEntity: 'endpoint', targetEntity: 'request', action: 'call'),
    OntologyRelationship(sourceEntity: 'endpoint', targetEntity: 'response', action: 'receive'),
    OntologyRelationship(sourceEntity: 'request', targetEntity: 'response', action: 'send'),
    OntologyRelationship(sourceEntity: 'event', targetEntity: 'webhook', action: 'trigger'),
    OntologyRelationship(sourceEntity: 'webhook', targetEntity: 'event', action: 'deliver'),
    OntologyRelationship(sourceEntity: 'apiKey', targetEntity: 'endpoint', action: 'call'),
    OntologyRelationship(sourceEntity: 'schema', targetEntity: 'request', action: 'create'),
    OntologyRelationship(sourceEntity: 'response', targetEntity: 'event', action: 'trigger'),
    OntologyRelationship(sourceEntity: 'rateLimit', targetEntity: 'request', action: 'send'),
    OntologyRelationship(sourceEntity: 'apiKey', targetEntity: 'apiKey', action: 'create'),
    OntologyRelationship(sourceEntity: 'endpoint', targetEntity: 'schema', action: 'receive'),
  ],
);
