import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final medicalDomain = DomainOntology(
  id: 'medical',
  displayName: 'Medical',
  synonyms: [
    'medical', 'healthcare', 'health', 'patient', 'clinical',
    'hospital', 'clinic', 'telehealth', 'prescription',
  ],
  entities: {
    'patient': EntityDef(
      id: 'patient',
      displayName: 'Patient',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'P-001234',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Full name',
          type: PropertyType.string,
          required: true,
          example: 'Jane Smith',
          minLength: 2,
          maxLength: 150,
        ),
        PropertyDef(
          name: 'dob',
          displayName: 'Date of birth',
          type: PropertyType.date,
          required: true,
          example: '1990-05-15',
          invalidExample: '2026-01-01',
        ),
        PropertyDef(
          name: 'email',
          displayName: 'Email address',
          type: PropertyType.email,
          example: 'jane.smith@example.com',
          invalidExample: 'not-email',
          pattern: r'^[^@]+@[^@]+\.[^@]+$',
        ),
        PropertyDef(
          name: 'phone',
          displayName: 'Phone number',
          type: PropertyType.phone,
          example: '+1-555-0123',
          invalidExample: 'abc',
        ),
        PropertyDef(
          name: 'address',
          displayName: 'Address',
          type: PropertyType.string,
          example: '123 Main St, Springfield, IL 62701',
        ),
        PropertyDef(
          name: 'bloodType',
          displayName: 'Blood type',
          type: PropertyType.enum_,
          enumValues: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
          example: 'O+',
        ),
        PropertyDef(
          name: 'allergies',
          displayName: 'Allergies',
          type: PropertyType.string,
          example: 'Penicillin, Peanuts',
        ),
        PropertyDef(
          name: 'insuranceId',
          displayName: 'Insurance ID',
          type: PropertyType.string,
          isSensitive: true,
          example: 'INS-98765-XY',
          invalidExample: 'N/A',
        ),
      ],
    ),
    'provider': EntityDef(
      id: 'provider',
      displayName: 'Provider',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Provider ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'DOC-0042',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Provider name',
          type: PropertyType.string,
          required: true,
          example: 'Dr. Emily Carter',
          minLength: 2,
          maxLength: 150,
        ),
        PropertyDef(
          name: 'specialty',
          displayName: 'Specialty',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Cardiology', 'Dermatology', 'Neurology', 'Pediatrics', 'Orthopedics', 'General', 'Psychiatry', 'Radiology'],
          example: 'Cardiology',
        ),
        PropertyDef(
          name: 'npiNumber',
          displayName: 'NPI number',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: '1234567893',
          invalidExample: '0000000000',
          pattern: r'^\d{10}$',
        ),
        PropertyDef(
          name: 'email',
          displayName: 'Email address',
          type: PropertyType.email,
          example: 'dr.carter@hospital.example.com',
          invalidExample: 'not-email',
        ),
        PropertyDef(
          name: 'phone',
          displayName: 'Phone number',
          type: PropertyType.phone,
          required: true,
          example: '+1-555-0199',
        ),
        PropertyDef(
          name: 'availability',
          displayName: 'Availability',
          type: PropertyType.string,
          example: 'Mon-Fri 9am-5pm',
        ),
      ],
    ),
    'appointment': EntityDef(
      id: 'appointment',
      displayName: 'Appointment',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Appointment ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'APT-0042',
        ),
        PropertyDef(
          name: 'patientId',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          example: 'P-001234',
        ),
        PropertyDef(
          name: 'providerId',
          displayName: 'Provider ID',
          type: PropertyType.string,
          required: true,
          example: 'DOC-0042',
        ),
        PropertyDef(
          name: 'date',
          displayName: 'Appointment date',
          type: PropertyType.date,
          required: true,
          example: '2026-07-15',
        ),
        PropertyDef(
          name: 'time',
          displayName: 'Appointment time',
          type: PropertyType.string,
          required: true,
          example: '10:30',
        ),
        PropertyDef(
          name: 'duration',
          displayName: 'Duration (minutes)',
          type: PropertyType.integer,
          example: '30',
          boundaryLow: '15',
          boundaryHigh: '120',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: ['Scheduled', 'Confirmed', 'In Progress', 'Completed', 'Cancelled', 'No Show'],
          example: 'Scheduled',
        ),
        PropertyDef(
          name: 'reason',
          displayName: 'Reason for visit',
          type: PropertyType.string,
          required: true,
          example: 'Chest pain follow-up',
        ),
        PropertyDef(
          name: 'notes',
          displayName: 'Notes',
          type: PropertyType.text,
          example: 'Patient requested morning slot',
        ),
      ],
    ),
    'record': EntityDef(
      id: 'record',
      displayName: 'Medical record',
      pluralDisplayName: 'Medical records',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Record ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'REC-0088',
        ),
        PropertyDef(
          name: 'patientId',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          example: 'P-001234',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Record type',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Progress Note', 'Discharge Summary', 'Consultation Note', 'Operative Report', 'Imaging Report'],
          example: 'Progress Note',
        ),
        PropertyDef(
          name: 'date',
          displayName: 'Record date',
          type: PropertyType.date,
          required: true,
          example: '2026-07-10',
        ),
        PropertyDef(
          name: 'provider',
          displayName: 'Provider',
          type: PropertyType.string,
          required: true,
          example: 'Dr. Emily Carter',
        ),
        PropertyDef(
          name: 'summary',
          displayName: 'Summary',
          type: PropertyType.text,
          required: true,
          example: 'Patient presented with mild hypertension...',
        ),
        PropertyDef(
          name: 'attachmentUrls',
          displayName: 'Attachment URLs',
          type: PropertyType.url,
          example: 'https://storage.example.com/records/rec0088.pdf',
        ),
      ],
    ),
    'labResult': EntityDef(
      id: 'labResult',
      displayName: 'Lab result',
      pluralDisplayName: 'Lab results',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Lab result ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'LAB-0056',
        ),
        PropertyDef(
          name: 'patientId',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          example: 'P-001234',
        ),
        PropertyDef(
          name: 'testName',
          displayName: 'Test name',
          type: PropertyType.string,
          required: true,
          example: 'Complete Blood Count',
        ),
        PropertyDef(
          name: 'result',
          displayName: 'Result',
          type: PropertyType.string,
          required: true,
          example: '5.2 x10^9/L',
        ),
        PropertyDef(
          name: 'referenceRange',
          displayName: 'Reference range',
          type: PropertyType.string,
          example: '4.0-11.0 x10^9/L',
        ),
        PropertyDef(
          name: 'date',
          displayName: 'Test date',
          type: PropertyType.date,
          required: true,
          example: '2026-07-08',
        ),
        PropertyDef(
          name: 'orderedBy',
          displayName: 'Ordered by',
          type: PropertyType.string,
          required: true,
          example: 'Dr. Emily Carter',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: ['Pending', 'Submitted', 'Reviewed', 'Completed', 'Cancelled'],
          example: 'Pending',
        ),
      ],
    ),
    'prescription': EntityDef(
      id: 'prescription',
      displayName: 'Prescription',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Prescription ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'RX-0033',
        ),
        PropertyDef(
          name: 'patientId',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          example: 'P-001234',
        ),
        PropertyDef(
          name: 'medication',
          displayName: 'Medication',
          type: PropertyType.string,
          required: true,
          example: 'Lisinopril 10mg',
        ),
        PropertyDef(
          name: 'dosage',
          displayName: 'Dosage',
          type: PropertyType.string,
          required: true,
          example: '1 tablet daily',
        ),
        PropertyDef(
          name: 'frequency',
          displayName: 'Frequency',
          type: PropertyType.string,
          required: true,
          example: 'Once per day',
        ),
        PropertyDef(
          name: 'refills',
          displayName: 'Refills',
          type: PropertyType.integer,
          example: '3',
          boundaryLow: '0',
          boundaryHigh: '12',
        ),
        PropertyDef(
          name: 'expiresAt',
          displayName: 'Expires at',
          type: PropertyType.date,
          example: '2027-01-08',
        ),
        PropertyDef(
          name: 'prescribedBy',
          displayName: 'Prescribed by',
          type: PropertyType.string,
          required: true,
          example: 'Dr. Emily Carter',
        ),
      ],
    ),
    'insurance': EntityDef(
      id: 'insurance',
      displayName: 'Insurance',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Insurance record ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'INS-001',
        ),
        PropertyDef(
          name: 'provider',
          displayName: 'Insurance provider',
          type: PropertyType.string,
          required: true,
          example: 'Blue Cross Blue Shield',
        ),
        PropertyDef(
          name: 'policyNumber',
          displayName: 'Policy number',
          type: PropertyType.string,
          required: true,
          isSensitive: true,
          isIdentifier: true,
          example: 'POL-987654-01',
          invalidExample: 'N/A',
        ),
        PropertyDef(
          name: 'groupNumber',
          displayName: 'Group number',
          type: PropertyType.string,
          isSensitive: true,
          example: 'GRP-4455',
        ),
        PropertyDef(
          name: 'coverageType',
          displayName: 'Coverage type',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Medical', 'Dental', 'Vision', 'Pharmacy'],
          example: 'Medical',
        ),
        PropertyDef(
          name: 'expiryDate',
          displayName: 'Expiry date',
          type: PropertyType.date,
          example: '2027-12-31',
        ),
        PropertyDef(
          name: 'copay',
          displayName: 'Copay',
          type: PropertyType.string,
          example: '\$30',
        ),
      ],
    ),
    'consent': EntityDef(
      id: 'consent',
      displayName: 'Consent',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Consent ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'CNT-0077',
        ),
        PropertyDef(
          name: 'patientId',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          example: 'P-001234',
        ),
        PropertyDef(
          name: 'documentType',
          displayName: 'Document type',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Treatment Consent', 'Data Sharing', 'Research Participation', 'HIPAA Authorization'],
          example: 'Treatment Consent',
        ),
        PropertyDef(
          name: 'signedAt',
          displayName: 'Signed at',
          type: PropertyType.date,
          required: true,
          example: '2026-06-01T10:00:00Z',
        ),
        PropertyDef(
          name: 'expiresAt',
          displayName: 'Expires at',
          type: PropertyType.date,
          example: '2027-06-01T10:00:00Z',
        ),
        PropertyDef(
          name: 'scope',
          displayName: 'Scope',
          type: PropertyType.string,
          required: true,
          example: 'All treatments at Springfield General',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Revoked', 'Expired'],
          example: 'Active',
        ),
      ],
    ),
    'allergy': EntityDef(
      id: 'allergy',
      displayName: 'Allergy',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Allergy ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'ALG-0022',
        ),
        PropertyDef(
          name: 'patientId',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          example: 'P-001234',
        ),
        PropertyDef(
          name: 'allergen',
          displayName: 'Allergen',
          type: PropertyType.string,
          required: true,
          example: 'Penicillin',
        ),
        PropertyDef(
          name: 'reaction',
          displayName: 'Reaction',
          type: PropertyType.string,
          required: true,
          example: 'Hives, difficulty breathing',
        ),
        PropertyDef(
          name: 'severity',
          displayName: 'Severity',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['Mild', 'Moderate', 'Severe', 'Life-threatening'],
          example: 'Severe',
        ),
        PropertyDef(
          name: 'diagnosedAt',
          displayName: 'Diagnosed at',
          type: PropertyType.date,
          example: '2018-03-12',
        ),
      ],
    ),
    'consultation': EntityDef(
      id: 'consultation',
      displayName: 'Consultation',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Consultation ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'CON-0099',
        ),
        PropertyDef(
          name: 'patientId',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          example: 'P-001234',
        ),
        PropertyDef(
          name: 'providerId',
          displayName: 'Provider ID',
          type: PropertyType.string,
          required: true,
          example: 'DOC-0042',
        ),
        PropertyDef(
          name: 'date',
          displayName: 'Consultation date',
          type: PropertyType.date,
          required: true,
          example: '2026-07-14',
        ),
        PropertyDef(
          name: 'duration',
          displayName: 'Duration (minutes)',
          type: PropertyType.integer,
          example: '45',
          boundaryLow: '15',
          boundaryHigh: '180',
        ),
        PropertyDef(
          name: 'mode',
          displayName: 'Consultation mode',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['In-Person', 'Video', 'Phone'],
          example: 'Video',
        ),
        PropertyDef(
          name: 'notes',
          displayName: 'Consultation notes',
          type: PropertyType.text,
          example: 'Discussed treatment plan and medication adjustments',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: ['Scheduled', 'In Progress', 'Completed', 'Cancelled'],
          example: 'Scheduled',
        ),
      ],
    ),
  },
  actions: {
    'schedule': ActionDef(
      id: 'schedule',
      displayName: 'Schedule',
      verb: 'Schedule',
      pastTense: 'scheduled',
      preposition: 'for',
      category: ActionCategory.scheduling,
      requiredPropertyNames: ['patientId', 'providerId', 'date', 'time'],
      optionalPropertyNames: ['duration', 'reason', 'notes'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'active', condition: 'confirmed'),
        StateTransition(fromState: 'pending', toState: 'cancelled', condition: 'cancelled'),
      ],
    ),
    'view': ActionDef(
      id: 'view',
      displayName: 'View',
      verb: 'View',
      pastTense: 'viewed',
      preposition: 'by',
      category: ActionCategory.navigation,
      requiredPropertyNames: ['patientId'],
      optionalPropertyNames: ['id'],
    ),
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      category: ActionCategory.crud,
      requiredPropertyNames: ['patientId'],
      optionalPropertyNames: ['type', 'summary', 'date'],
      transitions: [
        StateTransition(fromState: 'inactive', toState: 'active', condition: 'saved'),
        StateTransition(fromState: 'pending', toState: 'submitted', condition: 'submitted'),
      ],
    ),
    'update': ActionDef(
      id: 'update',
      displayName: 'Update',
      verb: 'Update',
      pastTense: 'updated',
      category: ActionCategory.crud,
      requiredPropertyNames: ['id'],
      optionalPropertyNames: ['summary', 'notes', 'status'],
    ),
    'cancel': ActionDef(
      id: 'cancel',
      displayName: 'Cancel',
      verb: 'Cancel',
      pastTense: 'cancelled',
      category: ActionCategory.administration,
      requiredPropertyNames: ['id'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'cancelled', condition: 'cancelled'),
        StateTransition(fromState: 'pending', toState: 'cancelled', condition: 'cancelled'),
      ],
    ),
    'requestRefill': ActionDef(
      id: 'requestRefill',
      displayName: 'Request refill',
      verb: 'Request refill',
      pastTense: 'requested refill',
      preposition: 'for',
      category: ActionCategory.commerce,
      requiredPropertyNames: ['id', 'patientId'],
      optionalPropertyNames: ['medication', 'dosage'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'pending', condition: 'requested'),
        StateTransition(fromState: 'active', toState: 'denied', condition: 'denied'),
      ],
    ),
    'share': ActionDef(
      id: 'share',
      displayName: 'Share',
      verb: 'Share',
      pastTense: 'shared',
      preposition: 'with',
      category: ActionCategory.sharing,
      requiredPropertyNames: ['patientId'],
      optionalPropertyNames: ['id', 'attachmentUrls'],
    ),
    'authorize': ActionDef(
      id: 'authorize',
      displayName: 'Authorize',
      verb: 'Authorize',
      pastTense: 'authorized',
      preposition: 'for',
      category: ActionCategory.auth,
      requiredPropertyNames: ['patientId', 'documentType', 'scope'],
      optionalPropertyNames: ['expiresAt'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'active', condition: 'signed'),
        StateTransition(fromState: 'active', toState: 'expired', condition: 'expired'),
        StateTransition(fromState: 'active', toState: 'denied', condition: 'revoked'),
      ],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'pending': StateDef(id: 'pending', displayName: 'Pending'),
      'completed': StateDef(id: 'completed', displayName: 'Completed', isTerminal: true),
      'cancelled': StateDef(id: 'cancelled', displayName: 'Cancelled', isTerminal: true),
      'expired': StateDef(id: 'expired', displayName: 'Expired', isTerminal: true),
      'submitted': StateDef(id: 'submitted', displayName: 'Submitted'),
      'reviewed': StateDef(id: 'reviewed', displayName: 'Reviewed'),
      'denied': StateDef(id: 'denied', displayName: 'Denied', isTerminal: true),
    },
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'appointment', action: 'schedule'),
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'patient', action: 'view'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'record', action: 'create'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'record', action: 'view'),
    OntologyRelationship(sourceEntity: 'record', targetEntity: 'provider', action: 'update'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'labResult', action: 'view'),
    OntologyRelationship(sourceEntity: 'provider', targetEntity: 'labResult', action: 'create'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'prescription', action: 'requestRefill'),
    OntologyRelationship(sourceEntity: 'provider', targetEntity: 'prescription', action: 'create'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'insurance', action: 'create'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'insurance', action: 'view'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'consent', action: 'authorize'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'allergy', action: 'create'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'allergy', action: 'view'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'consultation', action: 'schedule'),
    OntologyRelationship(sourceEntity: 'provider', targetEntity: 'consultation', action: 'create'),
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'consultation', action: 'create'),
  ],
);
