import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final roboticsDomain = DomainOntology(
  id: 'robotics',
  displayName: 'Robotics',
  synonyms: [
    'robotics', 'robot', 'automation', 'drone',
    'autonomous', 'iot', 'fleet',
  ],
  entities: {
    'robot': EntityDef(
      id: 'robot',
      displayName: 'Robot',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Robot ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'robot-a1b2c3',
          invalidExample: '',
          pattern: r'^robot-[a-z0-9]+$',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Robot name',
          type: PropertyType.string,
          example: 'Atlas-007',
          minLength: 1,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'model',
          displayName: 'Model',
          type: PropertyType.string,
          example: 'R2025-Industrial',
        ),
        PropertyDef(
          name: 'serialNumber',
          displayName: 'Serial number',
          type: PropertyType.string,
          isIdentifier: true,
          example: 'SN-98765-ABC',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'firmware',
          displayName: 'Firmware version',
          type: PropertyType.string,
          example: 'v3.2.1',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Robot status',
          type: PropertyType.enum_,
          enumValues: [
            'Active', 'Inactive', 'Idle', 'Running',
            'Paused', 'Charging', 'Maintenance', 'Failed',
          ],
          example: 'Active',
        ),
        PropertyDef(
          name: 'batteryLevel',
          displayName: 'Battery level',
          type: PropertyType.percent,
          example: '85',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'location',
          displayName: 'Location',
          type: PropertyType.coordinates,
          example: '37.7749,-122.4194',
          invalidExample: '999,999',
        ),
        PropertyDef(
          name: 'lastMaintenance',
          displayName: 'Last maintenance',
          type: PropertyType.date,
          example: '2026-06-15T10:00:00Z',
        ),
      ],
    ),
    'task': EntityDef(
      id: 'task',
      displayName: 'Task',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Task ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'task-9x8y7z',
          pattern: r'^task-[a-z0-9]+$',
        ),
        PropertyDef(
          name: 'robotId',
          displayName: 'Robot ID',
          type: PropertyType.string,
          required: true,
          example: 'robot-a1b2c3',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Task type',
          type: PropertyType.enum_,
          enumValues: [
            'Navigation', 'Manipulation', 'Inspection',
            'Transport', 'Assembly', 'Cleaning',
          ],
          example: 'Inspection',
        ),
        PropertyDef(
          name: 'priority',
          displayName: 'Priority',
          type: PropertyType.enum_,
          enumValues: ['Low', 'Medium', 'High', 'Critical'],
          example: 'High',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Task status',
          type: PropertyType.enum_,
          enumValues: [
            'Pending', 'Running', 'Paused', 'Completed', 'Failed',
          ],
          example: 'Running',
        ),
        PropertyDef(
          name: 'assignedAt',
          displayName: 'Assigned at',
          type: PropertyType.date,
          example: '2026-06-28T08:00:00Z',
        ),
        PropertyDef(
          name: 'startedAt',
          displayName: 'Started at',
          type: PropertyType.date,
          example: '2026-06-28T08:05:00Z',
        ),
        PropertyDef(
          name: 'completedAt',
          displayName: 'Completed at',
          type: PropertyType.date,
          example: '2026-06-28T08:30:00Z',
        ),
        PropertyDef(
          name: 'params',
          displayName: 'Task parameters',
          type: PropertyType.text,
          example: '{"zone": "A12", "depth": 3}',
        ),
      ],
    ),
    'mission': EntityDef(
      id: 'mission',
      displayName: 'Mission',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Mission ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'mission-m1n2o3',
          pattern: r'^mission-[a-z0-9]+$',
        ),
        PropertyDef(
          name: 'robotId',
          displayName: 'Robot ID',
          type: PropertyType.string,
          required: true,
          example: 'robot-a1b2c3',
        ),
        PropertyDef(
          name: 'waypoints',
          displayName: 'Waypoints',
          type: PropertyType.text,
          example: '["wp_001", "wp_002", "wp_003"]',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Mission status',
          type: PropertyType.enum_,
          enumValues: [
            'Planned', 'Running', 'Paused', 'Completed', 'Failed',
          ],
          example: 'Running',
        ),
        PropertyDef(
          name: 'startedAt',
          displayName: 'Started at',
          type: PropertyType.date,
          example: '2026-06-28T09:00:00Z',
        ),
        PropertyDef(
          name: 'completedAt',
          displayName: 'Completed at',
          type: PropertyType.date,
          example: '2026-06-28T09:45:00Z',
        ),
        PropertyDef(
          name: 'distance',
          displayName: 'Distance (meters)',
          type: PropertyType.number,
          example: '1500',
          boundaryLow: '0',
          boundaryHigh: '100000',
        ),
        PropertyDef(
          name: 'duration',
          displayName: 'Duration (seconds)',
          type: PropertyType.integer,
          example: '2700',
          boundaryLow: '0',
          boundaryHigh: '86400',
        ),
      ],
    ),
    'sensor': EntityDef(
      id: 'sensor',
      displayName: 'Sensor',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Sensor ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'sns-temp-01',
          pattern: r'^sns-[a-z]+-\d+$',
        ),
        PropertyDef(
          name: 'robotId',
          displayName: 'Robot ID',
          type: PropertyType.string,
          required: true,
          example: 'robot-a1b2c3',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Sensor type',
          type: PropertyType.enum_,
          enumValues: [
            'Temperature', 'Pressure', 'Proximity', 'Lidar',
            'Camera', 'IMU', 'Ultrasonic', 'Gas',
          ],
          example: 'Lidar',
        ),
        PropertyDef(
          name: 'value',
          displayName: 'Reading value',
          type: PropertyType.number,
          example: '23.5',
        ),
        PropertyDef(
          name: 'unit',
          displayName: 'Unit',
          type: PropertyType.string,
          example: '°C',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Sensor status',
          type: PropertyType.enum_,
          enumValues: ['Operational', 'Faulty', 'Offline', 'Calibrating'],
          example: 'Operational',
        ),
        PropertyDef(
          name: 'lastCalibrated',
          displayName: 'Last calibrated',
          type: PropertyType.date,
          example: '2026-06-01T12:00:00Z',
        ),
        PropertyDef(
          name: 'precision',
          displayName: 'Precision',
          type: PropertyType.number,
          example: '0.01',
          boundaryLow: '0',
          boundaryHigh: '1',
        ),
      ],
    ),
    'actuator': EntityDef(
      id: 'actuator',
      displayName: 'Actuator',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Actuator ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'act-joint-03',
          pattern: r'^act-[a-z]+-\d+$',
        ),
        PropertyDef(
          name: 'robotId',
          displayName: 'Robot ID',
          type: PropertyType.string,
          required: true,
          example: 'robot-a1b2c3',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Actuator type',
          type: PropertyType.enum_,
          enumValues: [
            'Linear', 'Rotary', 'Servo', 'Stepper',
            'Pneumatic', 'Hydraulic',
          ],
          example: 'Servo',
        ),
        PropertyDef(
          name: 'position',
          displayName: 'Position',
          type: PropertyType.number,
          example: '45.0',
          boundaryLow: '-180',
          boundaryHigh: '180',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Actuator status',
          type: PropertyType.enum_,
          enumValues: ['Operational', 'Faulty', 'Offline', 'Overheated'],
          example: 'Operational',
        ),
        PropertyDef(
          name: 'maxTorque',
          displayName: 'Max torque (Nm)',
          type: PropertyType.number,
          example: '12.5',
          boundaryLow: '0',
          boundaryHigh: '500',
        ),
        PropertyDef(
          name: 'temperature',
          displayName: 'Temperature (°C)',
          type: PropertyType.number,
          example: '42.3',
          boundaryLow: '-20',
          boundaryHigh: '150',
        ),
      ],
    ),
    'waypoint': EntityDef(
      id: 'waypoint',
      displayName: 'Waypoint',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Waypoint ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'wp-001',
          pattern: r'^wp-\d+$',
        ),
        PropertyDef(
          name: 'missionId',
          displayName: 'Mission ID',
          type: PropertyType.string,
          required: true,
          example: 'mission-m1n2o3',
        ),
        PropertyDef(
          name: 'latitude',
          displayName: 'Latitude',
          type: PropertyType.number,
          required: true,
          example: '37.7749',
          boundaryLow: '-90',
          boundaryHigh: '90',
        ),
        PropertyDef(
          name: 'longitude',
          displayName: 'Longitude',
          type: PropertyType.number,
          required: true,
          example: '-122.4194',
          boundaryLow: '-180',
          boundaryHigh: '180',
        ),
        PropertyDef(
          name: 'altitude',
          displayName: 'Altitude (meters)',
          type: PropertyType.number,
          example: '15.0',
          boundaryLow: '-500',
          boundaryHigh: '10000',
        ),
        PropertyDef(
          name: 'order',
          displayName: 'Sequence order',
          type: PropertyType.integer,
          required: true,
          example: '1',
          boundaryLow: '0',
          boundaryHigh: '999',
        ),
        PropertyDef(
          name: 'tolerance',
          displayName: 'Tolerance (meters)',
          type: PropertyType.number,
          example: '0.5',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
      ],
    ),
    'battery': EntityDef(
      id: 'battery',
      displayName: 'Battery',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Battery ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'bat-li-04',
          pattern: r'^bat-[a-z]+-\d+$',
        ),
        PropertyDef(
          name: 'robotId',
          displayName: 'Robot ID',
          type: PropertyType.string,
          required: true,
          example: 'robot-a1b2c3',
        ),
        PropertyDef(
          name: 'level',
          displayName: 'Charge level',
          type: PropertyType.percent,
          example: '72',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'voltage',
          displayName: 'Voltage (V)',
          type: PropertyType.number,
          example: '48.2',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'temperature',
          displayName: 'Temperature (°C)',
          type: PropertyType.number,
          example: '35.0',
          boundaryLow: '-10',
          boundaryHigh: '80',
        ),
        PropertyDef(
          name: 'cycleCount',
          displayName: 'Cycle count',
          type: PropertyType.integer,
          example: '320',
          boundaryLow: '0',
          boundaryHigh: '10000',
        ),
        PropertyDef(
          name: 'health',
          displayName: 'Health',
          type: PropertyType.percent,
          example: '92',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'charging',
          displayName: 'Is charging',
          type: PropertyType.boolean,
          example: 'false',
        ),
      ],
    ),
    'diagnostic': EntityDef(
      id: 'diagnostic',
      displayName: 'Diagnostic',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Diagnostic ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'diag-20260628-01',
          pattern: r'^diag-\d{8}-\d+$',
        ),
        PropertyDef(
          name: 'robotId',
          displayName: 'Robot ID',
          type: PropertyType.string,
          required: true,
          example: 'robot-a1b2c3',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Diagnostic type',
          type: PropertyType.enum_,
          enumValues: [
            'System', 'Motor', 'Sensor', 'Battery',
            'Network', 'Firmware', 'Safety',
          ],
          example: 'Motor',
        ),
        PropertyDef(
          name: 'result',
          displayName: 'Result',
          type: PropertyType.enum_,
          enumValues: ['Pass', 'Fail', 'Warning', 'Error'],
          example: 'Pass',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Diagnostic status',
          type: PropertyType.enum_,
          enumValues: ['Pending', 'Running', 'Completed', 'Failed'],
          example: 'Completed',
        ),
        PropertyDef(
          name: 'checkedAt',
          displayName: 'Checked at',
          type: PropertyType.date,
          example: '2026-06-28T12:00:00Z',
        ),
        PropertyDef(
          name: 'details',
          displayName: 'Details',
          type: PropertyType.text,
          example: 'Motor encoder reading out of range on joint 3',
        ),
        PropertyDef(
          name: 'severity',
          displayName: 'Severity',
          type: PropertyType.enum_,
          enumValues: ['Info', 'Warning', 'Error', 'Critical'],
          example: 'Warning',
        ),
      ],
    ),
  },
  actions: {
    'start': ActionDef(
      id: 'start',
      displayName: 'Start',
      verb: 'Start',
      pastTense: 'started',
      preposition: 'on',
      category: ActionCategory.execution,
      requiredPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'idle', toState: 'running', condition: 'ready'),
        StateTransition(fromState: 'paused', toState: 'running', condition: 'resume'),
        StateTransition(fromState: 'inactive', toState: 'active', condition: 'power_on'),
      ],
    ),
    'stop': ActionDef(
      id: 'stop',
      displayName: 'Stop',
      verb: 'Stop',
      pastTense: 'stopped',
      preposition: 'on',
      category: ActionCategory.execution,
      requiredPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'running', toState: 'paused', condition: 'pause'),
        StateTransition(fromState: 'running', toState: 'idle', condition: 'emergency'),
      ],
    ),
    'calibrate': ActionDef(
      id: 'calibrate',
      displayName: 'Calibrate',
      verb: 'Calibrate',
      pastTense: 'calibrated',
      preposition: 'on',
      category: ActionCategory.administration,
      requiredPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'idle', toState: 'maintenance', condition: 'start_calibration'),
        StateTransition(fromState: 'maintenance', toState: 'idle', condition: 'calibration_done'),
      ],
    ),
    'diagnose': ActionDef(
      id: 'diagnose',
      displayName: 'Diagnose',
      verb: 'Diagnose',
      pastTense: 'diagnosed',
      preposition: 'for',
      category: ActionCategory.analytics,
      requiredPropertyNames: [],
      optionalPropertyNames: ['type'],
      transitions: [
        StateTransition(fromState: 'idle', toState: 'running', condition: 'diagnostic_started'),
        StateTransition(fromState: 'running', toState: 'completed', condition: 'diagnostic_done'),
        StateTransition(fromState: 'running', toState: 'failed', condition: 'diagnostic_error'),
      ],
    ),
    'configure': ActionDef(
      id: 'configure',
      displayName: 'Configure',
      verb: 'Configure',
      pastTense: 'configured',
      preposition: 'for',
      category: ActionCategory.administration,
      requiredPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'idle', toState: 'maintenance', condition: 'reconfig'),
        StateTransition(fromState: 'maintenance', toState: 'idle', condition: 'reconfig_done'),
      ],
    ),
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
    ),
    'execute': ActionDef(
      id: 'execute',
      displayName: 'Execute',
      verb: 'Execute',
      pastTense: 'executed',
      preposition: 'on',
      category: ActionCategory.execution,
      requiredPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'idle', toState: 'running', condition: 'execute_start'),
        StateTransition(fromState: 'running', toState: 'completed', condition: 'execute_done'),
        StateTransition(fromState: 'running', toState: 'failed', condition: 'execute_error'),
      ],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'idle': StateDef(id: 'idle', displayName: 'Idle'),
      'running': StateDef(id: 'running', displayName: 'Running'),
      'paused': StateDef(id: 'paused', displayName: 'Paused'),
      'completed': StateDef(id: 'completed', displayName: 'Completed', isTerminal: true),
      'failed': StateDef(id: 'failed', displayName: 'Failed'),
      'charging': StateDef(id: 'charging', displayName: 'Charging'),
      'maintenance': StateDef(id: 'maintenance', displayName: 'Maintenance'),
    },
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'robot', targetEntity: 'task', action: 'execute'),
    OntologyRelationship(sourceEntity: 'task', targetEntity: 'robot', action: 'start'),
    OntologyRelationship(sourceEntity: 'robot', targetEntity: 'mission', action: 'execute'),
    OntologyRelationship(sourceEntity: 'mission', targetEntity: 'waypoint', action: 'create'),
    OntologyRelationship(sourceEntity: 'robot', targetEntity: 'sensor', action: 'calibrate'),
    OntologyRelationship(sourceEntity: 'robot', targetEntity: 'actuator', action: 'configure'),
    OntologyRelationship(sourceEntity: 'robot', targetEntity: 'battery', action: 'start'),
    OntologyRelationship(sourceEntity: 'robot', targetEntity: 'diagnostic', action: 'diagnose'),
    OntologyRelationship(sourceEntity: 'diagnostic', targetEntity: 'robot', action: 'configure'),
    OntologyRelationship(sourceEntity: 'sensor', targetEntity: 'robot', action: 'execute'),
    OntologyRelationship(sourceEntity: 'actuator', targetEntity: 'robot', action: 'execute'),
    OntologyRelationship(sourceEntity: 'battery', targetEntity: 'robot', action: 'stop'),
  ],
);
