import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final schedulingDomain = DomainOntology(
  id: 'scheduling',
  displayName: 'Scheduling',
  synonyms: [
    'scheduling',
    'appointment',
    'booking',
    'calendar',
    'slot',
    'schedule',
    'reservation',
  ],
  entities: {
    'appointment': EntityDef(
      id: 'appointment',
      displayName: 'Appointment',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Appointment ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'APT-001',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'patientName',
          displayName: 'Patient name',
          type: PropertyType.string,
          required: true,
          example: 'Emily Davis',
          minLength: 2,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'providerName',
          displayName: 'Provider name',
          type: PropertyType.string,
          required: true,
          example: 'Dr. Sarah Lee',
        ),
        PropertyDef(
          name: 'date',
          displayName: 'Date',
          type: PropertyType.date,
          required: true,
          example: '2026-07-15',
          invalidExample: '15-07-2026',
        ),
        PropertyDef(
          name: 'time',
          displayName: 'Time',
          type: PropertyType.string,
          required: true,
          example: '10:30',
          invalidExample: '25:00',
          pattern: r'^\d{2}:\d{2}$',
        ),
        PropertyDef(
          name: 'duration',
          displayName: 'Duration',
          type: PropertyType.integer,
          example: '30',
          boundaryLow: '15',
          boundaryHigh: '180',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: [
            'Available',
            'Booked',
            'Confirmed',
            'Cancelled',
            'Completed',
            'Rescheduled',
          ],
          example: 'Booked',
        ),
        PropertyDef(
          name: 'reason',
          displayName: 'Reason',
          type: PropertyType.text,
          example: 'Annual physical checkup',
          maxLength: 500,
        ),
        PropertyDef(
          name: 'notes',
          displayName: 'Notes',
          type: PropertyType.text,
          example: 'Patient prefers morning appointments',
          maxLength: 1000,
        ),
        PropertyDef(
          name: 'reminderEnabled',
          displayName: 'Reminder enabled',
          type: PropertyType.boolean,
          example: 'true',
        ),
      ],
    ),
    'provider': EntityDef(
      id: 'provider',
      displayName: 'Provider',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Provider ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'PROV-042',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Name',
          type: PropertyType.string,
          required: true,
          example: 'Dr. Sarah Lee',
          minLength: 2,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'specialty',
          displayName: 'Specialty',
          type: PropertyType.string,
          example: 'Cardiology',
        ),
        PropertyDef(
          name: 'email',
          displayName: 'Email',
          type: PropertyType.email,
          example: 'sarah.lee@clinic.com',
          pattern: r'^[^@]+@[^@]+\.[^@]+$',
        ),
        PropertyDef(
          name: 'phone',
          displayName: 'Phone',
          type: PropertyType.phone,
          example: '+1-555-0123',
          pattern: r'^\+?\d{1,3}[\s-]?\d{3}[\s-]?\d{4}$',
        ),
        PropertyDef(
          name: 'maxPatientsPerDay',
          displayName: 'Max patients per day',
          type: PropertyType.integer,
          example: '20',
          boundaryLow: '1',
          boundaryHigh: '100',
        ),
      ],
    ),
    'patient': EntityDef(
      id: 'patient',
      displayName: 'Patient',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Patient ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'PAT-789',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Name',
          type: PropertyType.string,
          required: true,
          example: 'Emily Davis',
          minLength: 2,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'email',
          displayName: 'Email',
          type: PropertyType.email,
          example: 'emily.davis@example.com',
        ),
        PropertyDef(
          name: 'phone',
          displayName: 'Phone',
          type: PropertyType.phone,
          example: '+1-555-0456',
        ),
        PropertyDef(
          name: 'dob',
          displayName: 'Date of birth',
          type: PropertyType.date,
          example: '1990-03-22',
        ),
        PropertyDef(
          name: 'preferredProvider',
          displayName: 'Preferred provider',
          type: PropertyType.string,
          example: 'PROV-042',
        ),
      ],
    ),
    'slot': EntityDef(
      id: 'slot',
      displayName: 'Slot',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Slot ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'SLT-551',
        ),
        PropertyDef(
          name: 'providerId',
          displayName: 'Provider ID',
          type: PropertyType.string,
          required: true,
          example: 'PROV-042',
        ),
        PropertyDef(
          name: 'date',
          displayName: 'Date',
          type: PropertyType.date,
          required: true,
          example: '2026-07-15',
        ),
        PropertyDef(
          name: 'startTime',
          displayName: 'Start time',
          type: PropertyType.string,
          required: true,
          example: '09:00',
          pattern: r'^\d{2}:\d{2}$',
        ),
        PropertyDef(
          name: 'endTime',
          displayName: 'End time',
          type: PropertyType.string,
          required: true,
          example: '09:30',
          pattern: r'^\d{2}:\d{2}$',
        ),
        PropertyDef(
          name: 'isAvailable',
          displayName: 'Is available',
          type: PropertyType.boolean,
          example: 'true',
        ),
        PropertyDef(
          name: 'location',
          displayName: 'Location',
          type: PropertyType.string,
          example: 'Room 203, Main Clinic',
        ),
      ],
    ),
    'calendar': EntityDef(
      id: 'calendar',
      displayName: 'Calendar',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Calendar ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'CAL-PROV-042',
        ),
        PropertyDef(
          name: 'providerId',
          displayName: 'Provider ID',
          type: PropertyType.string,
          required: true,
          example: 'PROV-042',
        ),
        PropertyDef(
          name: 'date',
          displayName: 'Date',
          type: PropertyType.date,
          required: true,
          example: '2026-07-15',
        ),
        PropertyDef(
          name: 'slots',
          displayName: 'Slots',
          type: PropertyType.string,
          example: 'SLT-551, SLT-552, SLT-553',
        ),
        PropertyDef(
          name: 'workingHours',
          displayName: 'Working hours',
          type: PropertyType.string,
          example: '09:00-17:00',
        ),
        PropertyDef(
          name: 'timezone',
          displayName: 'Timezone',
          type: PropertyType.string,
          example: 'America/New_York',
        ),
      ],
    ),
    'availability': EntityDef(
      id: 'availability',
      displayName: 'Availability',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Availability ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'AVAIL-001',
        ),
        PropertyDef(
          name: 'providerId',
          displayName: 'Provider ID',
          type: PropertyType.string,
          required: true,
          example: 'PROV-042',
        ),
        PropertyDef(
          name: 'dayOfWeek',
          displayName: 'Day of week',
          type: PropertyType.enum_,
          required: true,
          enumValues: [
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday',
            'Sunday',
          ],
          example: 'Monday',
        ),
        PropertyDef(
          name: 'startTime',
          displayName: 'Start time',
          type: PropertyType.string,
          required: true,
          example: '09:00',
          pattern: r'^\d{2}:\d{2}$',
        ),
        PropertyDef(
          name: 'endTime',
          displayName: 'End time',
          type: PropertyType.string,
          required: true,
          example: '17:00',
          pattern: r'^\d{2}:\d{2}$',
        ),
        PropertyDef(
          name: 'recurrence',
          displayName: 'Recurrence',
          type: PropertyType.enum_,
          enumValues: ['Weekly', 'Biweekly', 'Monthly', 'None'],
          example: 'Weekly',
        ),
      ],
    ),
    'reminder': EntityDef(
      id: 'reminder',
      displayName: 'Reminder',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Reminder ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'REM-321',
        ),
        PropertyDef(
          name: 'appointmentId',
          displayName: 'Appointment ID',
          type: PropertyType.string,
          required: true,
          example: 'APT-001',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Type',
          type: PropertyType.enum_,
          enumValues: ['Email', 'SMS', 'Push notification'],
          example: 'Email',
        ),
        PropertyDef(
          name: 'sentAt',
          displayName: 'Sent at',
          type: PropertyType.date,
          example: '2026-07-14T10:00:00Z',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: ['Pending', 'Sent', 'Failed'],
          example: 'Sent',
        ),
        PropertyDef(
          name: 'channel',
          displayName: 'Channel',
          type: PropertyType.enum_,
          enumValues: ['email', 'sms', 'push'],
          example: 'email',
        ),
      ],
    ),
    'meetingLink': EntityDef(
      id: 'meetingLink',
      displayName: 'Meeting link',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Meeting link ID',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: 'ML-045',
        ),
        PropertyDef(
          name: 'appointmentId',
          displayName: 'Appointment ID',
          type: PropertyType.string,
          required: true,
          example: 'APT-001',
        ),
        PropertyDef(
          name: 'url',
          displayName: 'URL',
          type: PropertyType.url,
          required: true,
          example: 'https://zoom.us/j/123456789',
          invalidExample: 'not-a-url',
        ),
        PropertyDef(
          name: 'platform',
          displayName: 'Platform',
          type: PropertyType.enum_,
          enumValues: ['Zoom', 'Google Meet', 'Microsoft Teams', 'Webex'],
          example: 'Zoom',
        ),
        PropertyDef(
          name: 'expiresAt',
          displayName: 'Expires at',
          type: PropertyType.date,
          example: '2026-07-15T23:59:59Z',
        ),
      ],
    ),
  },
  actions: {
    'book': ActionDef(
      id: 'book',
      displayName: 'Book',
      verb: 'Book',
      pastTense: 'booked',
      preposition: 'for',
      category: ActionCategory.scheduling,
      requiredPropertyNames: ['patientName', 'providerName', 'date', 'time'],
      optionalPropertyNames: ['reason', 'notes', 'duration'],
      transitions: [
        StateTransition(fromState: 'available', toState: 'booked', condition: 'slot selected'),
        StateTransition(fromState: 'booked', toState: 'booked', condition: 'duplicate'),
      ],
    ),
    'confirm': ActionDef(
      id: 'confirm',
      displayName: 'Confirm',
      verb: 'Confirm',
      pastTense: 'confirmed',
      preposition: 'for',
      category: ActionCategory.scheduling,
      requiredPropertyNames: ['id'],
      transitions: [
        StateTransition(fromState: 'booked', toState: 'confirmed', condition: 'valid'),
        StateTransition(fromState: 'booked', toState: 'cancelled', condition: 'provider unavailable'),
      ],
    ),
    'cancel': ActionDef(
      id: 'cancel',
      displayName: 'Cancel',
      verb: 'Cancel',
      pastTense: 'cancelled',
      preposition: 'for',
      category: ActionCategory.scheduling,
      requiredPropertyNames: ['id'],
      optionalPropertyNames: ['reason'],
      transitions: [
        StateTransition(fromState: 'booked', toState: 'cancelled', condition: 'patient initiated'),
        StateTransition(fromState: 'confirmed', toState: 'cancelled', condition: 'patient initiated'),
      ],
    ),
    'reschedule': ActionDef(
      id: 'reschedule',
      displayName: 'Reschedule',
      verb: 'Reschedule',
      pastTense: 'rescheduled',
      preposition: 'to',
      category: ActionCategory.scheduling,
      requiredPropertyNames: ['id', 'date', 'time'],
      optionalPropertyNames: ['reason'],
      transitions: [
        StateTransition(fromState: 'confirmed', toState: 'rescheduled', condition: 'new slot selected'),
        StateTransition(fromState: 'rescheduled', toState: 'booked', condition: 'new appointment created'),
      ],
    ),
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      preposition: 'for',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
    ),
    'view': ActionDef(
      id: 'view',
      displayName: 'View',
      verb: 'View',
      pastTense: 'viewed',
      preposition: 'of',
      category: ActionCategory.crud,
      requiredPropertyNames: ['id'],
    ),
    'sendReminder': ActionDef(
      id: 'sendReminder',
      displayName: 'Send reminder',
      verb: 'Send reminder',
      pastTense: 'reminder sent',
      preposition: 'to',
      category: ActionCategory.communication,
      requiredPropertyNames: ['appointmentId', 'channel'],
      optionalPropertyNames: ['type'],
      transitions: [
        StateTransition(fromState: 'confirmed', toState: 'confirmed', condition: 'sent'),
      ],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'available': StateDef(id: 'available', displayName: 'Available'),
      'booked': StateDef(id: 'booked', displayName: 'Booked'),
      'confirmed': StateDef(id: 'confirmed', displayName: 'Confirmed'),
      'cancelled': StateDef(id: 'cancelled', displayName: 'Cancelled'),
      'completed': StateDef(id: 'completed', displayName: 'Completed', isTerminal: true),
      'rescheduled': StateDef(id: 'rescheduled', displayName: 'Rescheduled'),
      'unavailable': StateDef(id: 'unavailable', displayName: 'Unavailable'),
      'expired': StateDef(id: 'expired', displayName: 'Expired', isTerminal: true),
    },
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'patient', action: 'book'),
    OntologyRelationship(sourceEntity: 'patient', targetEntity: 'appointment', action: 'book'),
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'provider', action: 'book'),
    OntologyRelationship(sourceEntity: 'slot', targetEntity: 'appointment', action: 'book'),
    OntologyRelationship(sourceEntity: 'provider', targetEntity: 'calendar', action: 'create'),
    OntologyRelationship(sourceEntity: 'availability', targetEntity: 'slot', action: 'create'),
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'reminder', action: 'sendReminder'),
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'meetingLink', action: 'create'),
    OntologyRelationship(sourceEntity: 'calendar', targetEntity: 'slot', action: 'view'),
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'appointment', action: 'reschedule'),
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'appointment', action: 'cancel'),
    OntologyRelationship(sourceEntity: 'appointment', targetEntity: 'appointment', action: 'confirm'),
  ],
);
