import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final socialDomain = DomainOntology(
  id: 'social',
  displayName: 'Social',
  synonyms: [
    'social', 'social media', 'feed', 'post', 'message',
    'chat', 'community', 'network',
  ],
  entities: {
    'user': EntityDef(
      id: 'user',
      displayName: 'User',
      properties: [
        PropertyDef(
          name: 'username',
          displayName: 'Username',
          type: PropertyType.string,
          required: true,
          isIdentifier: true,
          example: '@alice',
          invalidExample: '@al ice',
          pattern: r'^@?\w{3,30}$',
          minLength: 3,
          maxLength: 30,
        ),
        PropertyDef(
          name: 'email',
          displayName: 'Email address',
          type: PropertyType.email,
          required: true,
          example: 'alice@example.com',
          invalidExample: 'not-an-email',
          pattern: r'^[^@]+@[^@]+\.[^@]+$',
        ),
        PropertyDef(
          name: 'displayName',
          displayName: 'Display name',
          type: PropertyType.string,
          example: 'Alice Johnson',
          minLength: 1,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'avatar',
          displayName: 'Avatar URL',
          type: PropertyType.url,
          example: 'https://cdn.example.com/avatars/alice.jpg',
          invalidExample: 'not-a-url',
        ),
        PropertyDef(
          name: 'bio',
          displayName: 'Bio',
          type: PropertyType.text,
          example: 'Software engineer & coffee enthusiast',
          maxLength: 500,
        ),
        PropertyDef(
          name: 'joinedAt',
          displayName: 'Joined date',
          type: PropertyType.date,
          example: '2025-01-15T08:30:00Z',
        ),
        PropertyDef(
          name: 'followerCount',
          displayName: 'Follower count',
          type: PropertyType.integer,
          example: '142',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'followingCount',
          displayName: 'Following count',
          type: PropertyType.integer,
          example: '89',
          boundaryLow: '0',
        ),
      ],
    ),
    'post': EntityDef(
      id: 'post',
      displayName: 'Post',
      properties: [
        PropertyDef(
          name: 'userId',
          displayName: 'Author ID',
          type: PropertyType.string,
          required: true,
          example: 'user_abc_001',
        ),
        PropertyDef(
          name: 'content',
          displayName: 'Content',
          type: PropertyType.text,
          required: true,
          example: 'Hello world! This is my first post.',
          maxLength: 5000,
        ),
        PropertyDef(
          name: 'mediaUrls',
          displayName: 'Media URLs',
          type: PropertyType.text,
          example: 'https://cdn.example.com/photo1.jpg,https://cdn.example.com/photo2.jpg',
          hint: 'Comma-separated URLs',
        ),
        PropertyDef(
          name: 'visibility',
          displayName: 'Visibility',
          type: PropertyType.enum_,
          enumValues: ['Public', 'Friends', 'Private'],
          example: 'Public',
        ),
        PropertyDef(
          name: 'createdAt',
          displayName: 'Created at',
          type: PropertyType.date,
          example: '2026-03-10T14:22:00Z',
        ),
        PropertyDef(
          name: 'likeCount',
          displayName: 'Like count',
          type: PropertyType.integer,
          example: '45',
          boundaryLow: '0',
        ),
        PropertyDef(
          name: 'commentCount',
          displayName: 'Comment count',
          type: PropertyType.integer,
          example: '12',
          boundaryLow: '0',
        ),
      ],
    ),
    'comment': EntityDef(
      id: 'comment',
      displayName: 'Comment',
      properties: [
        PropertyDef(
          name: 'postId',
          displayName: 'Post ID',
          type: PropertyType.string,
          required: true,
          example: 'post_xyz_789',
        ),
        PropertyDef(
          name: 'userId',
          displayName: 'Commenter ID',
          type: PropertyType.string,
          required: true,
          example: 'user_def_456',
        ),
        PropertyDef(
          name: 'content',
          displayName: 'Content',
          type: PropertyType.text,
          required: true,
          example: 'Great post! Thanks for sharing.',
          maxLength: 2000,
        ),
        PropertyDef(
          name: 'createdAt',
          displayName: 'Created at',
          type: PropertyType.date,
          example: '2026-03-10T15:00:00Z',
        ),
        PropertyDef(
          name: 'editedAt',
          displayName: 'Edited at',
          type: PropertyType.date,
          example: '2026-03-10T15:30:00Z',
        ),
      ],
    ),
    'like': EntityDef(
      id: 'like',
      displayName: 'Like',
      properties: [
        PropertyDef(
          name: 'postId',
          displayName: 'Post ID',
          type: PropertyType.string,
          required: true,
          example: 'post_xyz_789',
        ),
        PropertyDef(
          name: 'userId',
          displayName: 'User ID',
          type: PropertyType.string,
          required: true,
          example: 'user_ghi_012',
        ),
        PropertyDef(
          name: 'createdAt',
          displayName: 'Created at',
          type: PropertyType.date,
          example: '2026-03-10T15:05:00Z',
        ),
      ],
    ),
    'share': EntityDef(
      id: 'share',
      displayName: 'Share',
      properties: [
        PropertyDef(
          name: 'postId',
          displayName: 'Post ID',
          type: PropertyType.string,
          required: true,
          example: 'post_xyz_789',
        ),
        PropertyDef(
          name: 'userId',
          displayName: 'User ID',
          type: PropertyType.string,
          required: true,
          example: 'user_jkl_345',
        ),
        PropertyDef(
          name: 'platform',
          displayName: 'Platform',
          type: PropertyType.enum_,
          enumValues: ['Twitter', 'Facebook', 'LinkedIn', 'Copy link'],
          example: 'Twitter',
        ),
        PropertyDef(
          name: 'createdAt',
          displayName: 'Created at',
          type: PropertyType.date,
          example: '2026-03-10T16:00:00Z',
        ),
      ],
    ),
    'follow': EntityDef(
      id: 'follow',
      displayName: 'Follow',
      properties: [
        PropertyDef(
          name: 'followerId',
          displayName: 'Follower ID',
          type: PropertyType.string,
          required: true,
          example: 'user_mno_678',
        ),
        PropertyDef(
          name: 'followingId',
          displayName: 'Following ID',
          type: PropertyType.string,
          required: true,
          example: 'user_pqr_901',
        ),
        PropertyDef(
          name: 'createdAt',
          displayName: 'Created at',
          type: PropertyType.date,
          example: '2026-03-09T10:00:00Z',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Pending', 'Blocked'],
          example: 'Active',
        ),
      ],
    ),
    'message': EntityDef(
      id: 'message',
      displayName: 'Message',
      properties: [
        PropertyDef(
          name: 'senderId',
          displayName: 'Sender ID',
          type: PropertyType.string,
          required: true,
          example: 'user_stu_234',
        ),
        PropertyDef(
          name: 'receiverId',
          displayName: 'Receiver ID',
          type: PropertyType.string,
          required: true,
          example: 'user_vwx_567',
        ),
        PropertyDef(
          name: 'content',
          displayName: 'Content',
          type: PropertyType.text,
          required: true,
          example: 'Hey, are you free for a call?',
          maxLength: 10000,
        ),
        PropertyDef(
          name: 'mediaUrl',
          displayName: 'Media URL',
          type: PropertyType.url,
          example: 'https://cdn.example.com/files/doc.pdf',
        ),
        PropertyDef(
          name: 'sentAt',
          displayName: 'Sent at',
          type: PropertyType.date,
          example: '2026-03-10T17:30:00Z',
        ),
        PropertyDef(
          name: 'readAt',
          displayName: 'Read at',
          type: PropertyType.date,
          example: '2026-03-10T17:32:00Z',
        ),
      ],
    ),
    'notification': EntityDef(
      id: 'notification',
      displayName: 'Notification',
      properties: [
        PropertyDef(
          name: 'userId',
          displayName: 'Recipient ID',
          type: PropertyType.string,
          required: true,
          example: 'user_yza_890',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Notification type',
          type: PropertyType.enum_,
          required: true,
          enumValues: ['like', 'comment', 'follow', 'share', 'message', 'system'],
          example: 'like',
        ),
        PropertyDef(
          name: 'title',
          displayName: 'Title',
          type: PropertyType.string,
          required: true,
          example: 'Alice liked your post',
          maxLength: 200,
        ),
        PropertyDef(
          name: 'body',
          displayName: 'Body',
          type: PropertyType.text,
          example: 'Alice Johnson liked your photo "Sunset view"',
          maxLength: 500,
        ),
        PropertyDef(
          name: 'data',
          displayName: 'Data payload',
          type: PropertyType.text,
          example: '{"postId":"post_xyz_789","type":"like"}',
          hint: 'JSON-encoded metadata',
        ),
        PropertyDef(
          name: 'readAt',
          displayName: 'Read at',
          type: PropertyType.date,
          example: '2026-03-10T18:00:00Z',
        ),
        PropertyDef(
          name: 'createdAt',
          displayName: 'Created at',
          type: PropertyType.date,
          example: '2026-03-10T17:30:00Z',
        ),
      ],
    ),
  },
  actions: {
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'active', condition: 'approved'),
        StateTransition(fromState: 'pending', toState: 'deleted', condition: 'rejected'),
      ],
    ),
    'view': ActionDef(
      id: 'view',
      displayName: 'View',
      verb: 'View',
      pastTense: 'viewed',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
    ),
    'delete': ActionDef(
      id: 'delete',
      displayName: 'Delete',
      verb: 'Delete',
      pastTense: 'deleted',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'active', toState: 'deleted'),
        StateTransition(fromState: 'inactive', toState: 'deleted'),
        StateTransition(fromState: 'pending', toState: 'deleted'),
      ],
    ),
    'share': ActionDef(
      id: 'share',
      displayName: 'Share',
      verb: 'Share',
      pastTense: 'shared',
      preposition: 'to',
      category: ActionCategory.sharing,
      requiredPropertyNames: ['postId'],
      optionalPropertyNames: ['platform'],
    ),
    'send': ActionDef(
      id: 'send',
      displayName: 'Send',
      verb: 'Send',
      pastTense: 'sent',
      preposition: 'to',
      category: ActionCategory.communication,
      requiredPropertyNames: ['content', 'receiverId'],
      transitions: [
        StateTransition(fromState: 'pending', toState: 'sent'),
        StateTransition(fromState: 'sent', toState: 'delivered'),
        StateTransition(fromState: 'delivered', toState: 'read'),
      ],
    ),
    'like': ActionDef(
      id: 'like',
      displayName: 'Like',
      verb: 'Like',
      pastTense: 'liked',
      category: ActionCategory.crud,
      requiredPropertyNames: ['postId'],
    ),
    'follow': ActionDef(
      id: 'follow',
      displayName: 'Follow',
      verb: 'Follow',
      pastTense: 'followed',
      preposition: 'by',
      category: ActionCategory.crud,
      requiredPropertyNames: ['followingId'],
      transitions: [
        StateTransition(fromState: 'inactive', toState: 'active', condition: 'requested'),
        StateTransition(fromState: 'active', toState: 'inactive', condition: 'unfollowed'),
      ],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'pending': StateDef(id: 'pending', displayName: 'Pending'),
      'sent': StateDef(id: 'sent', displayName: 'Sent'),
      'delivered': StateDef(id: 'delivered', displayName: 'Delivered'),
      'read': StateDef(id: 'read', displayName: 'Read', isTerminal: true),
      'deleted': StateDef(id: 'deleted', displayName: 'Deleted', isTerminal: true),
    },
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'user', targetEntity: 'post', action: 'create'),
    OntologyRelationship(sourceEntity: 'post', targetEntity: 'user', action: 'view'),
    OntologyRelationship(sourceEntity: 'user', targetEntity: 'user', action: 'follow'),
    OntologyRelationship(sourceEntity: 'post', targetEntity: 'comment', action: 'create'),
    OntologyRelationship(sourceEntity: 'user', targetEntity: 'comment', action: 'create'),
    OntologyRelationship(sourceEntity: 'post', targetEntity: 'like', action: 'create'),
    OntologyRelationship(sourceEntity: 'user', targetEntity: 'like', action: 'like'),
    OntologyRelationship(sourceEntity: 'post', targetEntity: 'share', action: 'share'),
    OntologyRelationship(sourceEntity: 'user', targetEntity: 'share', action: 'share'),
    OntologyRelationship(sourceEntity: 'user', targetEntity: 'message', action: 'send'),
    OntologyRelationship(sourceEntity: 'message', targetEntity: 'user', action: 'send'),
    OntologyRelationship(sourceEntity: 'user', targetEntity: 'notification', action: 'view'),
  ],
);
