import '../../model/entity_def.dart';
import '../../model/action_def.dart';
import '../../model/state_def.dart';
import '../../model/domain_ontology.dart';

final techDomain = DomainOntology(
  id: 'tech',
  displayName: 'Technology',
  synonyms: [
    'tech', 'technology', 'devops', 'infrastructure', 'deployment',
    'server', 'cloud', 'kubernetes', 'docker',
  ],
  entities: {
    'server': EntityDef(
      id: 'server',
      displayName: 'Server',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Server ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'srv-prod-web-01',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'hostname',
          displayName: 'Hostname',
          type: PropertyType.string,
          required: true,
          example: 'web-01.prod.example.com',
          invalidExample: 'invalid hostname',
          pattern: r'^[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?)*$',
        ),
        PropertyDef(
          name: 'ipAddress',
          displayName: 'IP address',
          type: PropertyType.ipAddress,
          required: true,
          example: '10.0.1.42',
          invalidExample: '999.999.999.999',
        ),
        PropertyDef(
          name: 'os',
          displayName: 'Operating system',
          type: PropertyType.string,
          example: 'Ubuntu 22.04 LTS',
          invalidExample: '',
          minLength: 3,
          maxLength: 100,
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Server status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Inactive', 'Deploying', 'Failed', 'Degraded'],
          example: 'Active',
        ),
        PropertyDef(
          name: 'cpuCores',
          displayName: 'CPU cores',
          type: PropertyType.integer,
          example: '16',
          boundaryLow: '1',
          boundaryHigh: '256',
        ),
        PropertyDef(
          name: 'ramGb',
          displayName: 'RAM (GB)',
          type: PropertyType.integer,
          example: '64',
          boundaryLow: '1',
          boundaryHigh: '4096',
        ),
        PropertyDef(
          name: 'diskGb',
          displayName: 'Disk (GB)',
          type: PropertyType.integer,
          example: '1024',
          boundaryLow: '10',
          boundaryHigh: '102400',
        ),
        PropertyDef(
          name: 'region',
          displayName: 'Region',
          type: PropertyType.string,
          example: 'us-east-1',
          invalidExample: '',
        ),
      ],
    ),
    'deployment': EntityDef(
      id: 'deployment',
      displayName: 'Deployment',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Deployment ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'deploy-20260629-0042',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'version',
          displayName: 'Version',
          type: PropertyType.string,
          required: true,
          example: 'v2.5.1',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'service',
          displayName: 'Service name',
          type: PropertyType.string,
          required: true,
          example: 'api-gateway',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'environment',
          displayName: 'Environment',
          type: PropertyType.enum_,
          enumValues: ['Production', 'Staging', 'Development', 'Canary'],
          required: true,
          example: 'Production',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Deployment status',
          type: PropertyType.enum_,
          enumValues: ['Pending', 'Deploying', 'Running', 'Failed', 'RolledBack'],
          example: 'Running',
        ),
        PropertyDef(
          name: 'startedAt',
          displayName: 'Started at',
          type: PropertyType.date,
          example: '2026-06-29T02:00:00Z',
        ),
        PropertyDef(
          name: 'completedAt',
          displayName: 'Completed at',
          type: PropertyType.date,
          example: '2026-06-29T02:04:32Z',
        ),
        PropertyDef(
          name: 'commitHash',
          displayName: 'Commit hash',
          type: PropertyType.string,
          example: 'a1b2c3d4e5f67890abcdef1234567890abcdef12',
          pattern: r'^[a-f0-9]{40}$',
        ),
        PropertyDef(
          name: 'rolloutPercent',
          displayName: 'Rollout percentage',
          type: PropertyType.percent,
          example: '25',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
      ],
    ),
    'container': EntityDef(
      id: 'container',
      displayName: 'Container',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Container ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'abc123def456',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'image',
          displayName: 'Image',
          type: PropertyType.string,
          required: true,
          example: 'nginx:1.25-alpine',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'tag',
          displayName: 'Tag',
          type: PropertyType.string,
          example: '1.25-alpine',
          invalidExample: 'latest',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Container status',
          type: PropertyType.enum_,
          enumValues: ['Running', 'Stopped', 'Pending', 'Failed', 'Paused'],
          example: 'Running',
        ),
        PropertyDef(
          name: 'port',
          displayName: 'Port',
          type: PropertyType.port,
          example: '8080',
          invalidExample: '99999',
          boundaryLow: '1',
          boundaryHigh: '65535',
        ),
        PropertyDef(
          name: 'restartCount',
          displayName: 'Restart count',
          type: PropertyType.integer,
          example: '3',
          boundaryLow: '0',
          boundaryHigh: '999',
        ),
        PropertyDef(
          name: 'cpuLimit',
          displayName: 'CPU limit',
          type: PropertyType.string,
          example: '500m',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'memoryLimit',
          displayName: 'Memory limit',
          type: PropertyType.string,
          example: '512Mi',
          invalidExample: '',
        ),
      ],
    ),
    'service': EntityDef(
      id: 'service',
      displayName: 'Service',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Service ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'svc-api-gateway',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Service name',
          type: PropertyType.string,
          required: true,
          example: 'API Gateway',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'type',
          displayName: 'Service type',
          type: PropertyType.enum_,
          enumValues: ['ClusterIP', 'NodePort', 'LoadBalancer', 'ExternalName'],
          required: true,
          example: 'LoadBalancer',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Service status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Inactive', 'Degraded', 'Failed'],
          example: 'Active',
        ),
        PropertyDef(
          name: 'endpoint',
          displayName: 'Endpoint',
          type: PropertyType.url,
          example: 'https://api.example.com/v2',
          invalidExample: 'not-a-url',
        ),
        PropertyDef(
          name: 'port',
          displayName: 'Port',
          type: PropertyType.port,
          required: true,
          example: '443',
          boundaryLow: '1',
          boundaryHigh: '65535',
        ),
        PropertyDef(
          name: 'replicas',
          displayName: 'Replicas',
          type: PropertyType.integer,
          example: '3',
          boundaryLow: '0',
          boundaryHigh: '100',
        ),
        PropertyDef(
          name: 'healthEndpoint',
          displayName: 'Health endpoint',
          type: PropertyType.string,
          example: '/healthz',
          invalidExample: '',
        ),
      ],
    ),
    'config': EntityDef(
      id: 'config',
      displayName: 'Config',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Config ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'cfg-db-conn-42',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'service',
          displayName: 'Service',
          type: PropertyType.string,
          required: true,
          example: 'api-gateway',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'key',
          displayName: 'Config key',
          type: PropertyType.string,
          required: true,
          example: 'DB_CONNECTION_STRING',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'value',
          displayName: 'Config value',
          type: PropertyType.string,
          required: true,
          example: 'postgresql://user:pass@db-primary:5432/app',
          isSensitive: true,
        ),
        PropertyDef(
          name: 'version',
          displayName: 'Config version',
          type: PropertyType.integer,
          example: '5',
          boundaryLow: '1',
          boundaryHigh: '999999',
        ),
        PropertyDef(
          name: 'environment',
          displayName: 'Environment',
          type: PropertyType.enum_,
          enumValues: ['Production', 'Staging', 'Development'],
          example: 'Production',
        ),
        PropertyDef(
          name: 'isSecret',
          displayName: 'Is secret',
          type: PropertyType.boolean,
          example: 'true',
        ),
      ],
    ),
    'log': EntityDef(
      id: 'log',
      displayName: 'Log',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Log ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'log-abc123-def456',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'source',
          displayName: 'Log source',
          type: PropertyType.string,
          required: true,
          example: 'api-gateway',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'level',
          displayName: 'Log level',
          type: PropertyType.enum_,
          enumValues: ['DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL'],
          required: true,
          example: 'ERROR',
        ),
        PropertyDef(
          name: 'message',
          displayName: 'Log message',
          type: PropertyType.text,
          required: true,
          example: 'Connection timeout connecting to db-primary:5432',
          minLength: 1,
          maxLength: 10000,
        ),
        PropertyDef(
          name: 'timestamp',
          displayName: 'Timestamp',
          type: PropertyType.date,
          required: true,
          example: '2026-06-29T10:32:15.123Z',
        ),
        PropertyDef(
          name: 'traceId',
          displayName: 'Trace ID',
          type: PropertyType.string,
          example: 'trace-a1b2c3d4e5f6',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'metadata',
          displayName: 'Metadata',
          type: PropertyType.text,
          example: '{"requestId": "req_abc123", "userId": "user_42"}',
          maxLength: 5000,
        ),
      ],
    ),
    'metric': EntityDef(
      id: 'metric',
      displayName: 'Metric',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Metric ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'metric-cpu-20260629-1042',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Metric name',
          type: PropertyType.string,
          required: true,
          example: 'cpu_usage_percent',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'value',
          displayName: 'Value',
          type: PropertyType.number,
          required: true,
          example: '78.5',
          boundaryLow: '0',
          boundaryHigh: '999999.99',
        ),
        PropertyDef(
          name: 'unit',
          displayName: 'Unit',
          type: PropertyType.string,
          required: true,
          example: 'percent',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'timestamp',
          displayName: 'Timestamp',
          type: PropertyType.date,
          required: true,
          example: '2026-06-29T10:32:00Z',
        ),
        PropertyDef(
          name: 'source',
          displayName: 'Metric source',
          type: PropertyType.string,
          example: 'node_exporter',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'labels',
          displayName: 'Labels',
          type: PropertyType.text,
          example: '{"host": "web-01", "region": "us-east-1"}',
          maxLength: 2000,
        ),
      ],
    ),
    'alert': EntityDef(
      id: 'alert',
      displayName: 'Alert',
      properties: [
        PropertyDef(
          name: 'id',
          displayName: 'Alert ID',
          type: PropertyType.string,
          isIdentifier: true,
          required: true,
          example: 'alert-cpu-spike-42',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'name',
          displayName: 'Alert name',
          type: PropertyType.string,
          required: true,
          example: 'CPU usage above 90%',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'severity',
          displayName: 'Severity',
          type: PropertyType.enum_,
          enumValues: ['Critical', 'Warning', 'Info'],
          required: true,
          example: 'Critical',
        ),
        PropertyDef(
          name: 'status',
          displayName: 'Alert status',
          type: PropertyType.enum_,
          enumValues: ['Active', 'Acknowledged', 'Resolved', 'Silenced'],
          required: true,
          example: 'Active',
        ),
        PropertyDef(
          name: 'condition',
          displayName: 'Alert condition',
          type: PropertyType.string,
          required: true,
          example: 'cpu_usage_percent > 90 for 5m',
          invalidExample: '',
        ),
        PropertyDef(
          name: 'triggeredAt',
          displayName: 'Triggered at',
          type: PropertyType.date,
          required: true,
          example: '2026-06-29T10:30:00Z',
        ),
        PropertyDef(
          name: 'resolvedAt',
          displayName: 'Resolved at',
          type: PropertyType.date,
          example: '2026-06-29T10:45:00Z',
        ),
        PropertyDef(
          name: 'acknowledgedBy',
          displayName: 'Acknowledged by',
          type: PropertyType.string,
          example: 'ops-team-member',
          invalidExample: '',
        ),
      ],
    ),
  },
  actions: {
    'deploy': ActionDef(
      id: 'deploy',
      displayName: 'Deploy',
      verb: 'Deploy',
      pastTense: 'deployed',
      preposition: 'to',
      category: ActionCategory.deployment,
      requiredPropertyNames: ['version', 'service', 'environment'],
      optionalPropertyNames: ['commitHash', 'rolloutPercent'],
      transitions: [
        StateTransition(fromState: 'inactive', toState: 'deploying', condition: 'started'),
        StateTransition(fromState: 'deploying', toState: 'running', condition: 'success'),
        StateTransition(fromState: 'deploying', toState: 'failed', condition: 'error'),
      ],
    ),
    'configure': ActionDef(
      id: 'configure',
      displayName: 'Configure',
      verb: 'Configure',
      pastTense: 'configured',
      preposition: 'for',
      category: ActionCategory.administration,
      requiredPropertyNames: ['service', 'key', 'value'],
      optionalPropertyNames: ['environment', 'version', 'isSecret'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'active', condition: 'updated'),
        StateTransition(fromState: 'inactive', toState: 'active', condition: 'initialized'),
      ],
    ),
    'monitor': ActionDef(
      id: 'monitor',
      displayName: 'Monitor',
      verb: 'Monitor',
      pastTense: 'monitored',
      preposition: 'on',
      category: ActionCategory.analytics,
      requiredPropertyNames: ['name', 'value', 'source'],
      optionalPropertyNames: ['labels', 'unit'],
      transitions: [
        StateTransition(fromState: 'running', toState: 'degraded', condition: 'threshold breached'),
        StateTransition(fromState: 'degraded', toState: 'failed', condition: 'critical threshold'),
        StateTransition(fromState: 'degraded', toState: 'running', condition: 'recovered'),
      ],
    ),
    'backup': ActionDef(
      id: 'backup',
      displayName: 'Backup',
      verb: 'Back up',
      pastTense: 'backed up',
      preposition: 'to',
      category: ActionCategory.administration,
      requiredPropertyNames: ['id', 'source'],
      optionalPropertyNames: ['region'],
      transitions: [
        StateTransition(fromState: 'active', toState: 'active', condition: 'completed'),
        StateTransition(fromState: 'active', toState: 'failed', condition: 'error'),
      ],
    ),
    'restore': ActionDef(
      id: 'restore',
      displayName: 'Restore',
      verb: 'Restore',
      pastTense: 'restored',
      preposition: 'from',
      category: ActionCategory.administration,
      requiredPropertyNames: ['id'],
      optionalPropertyNames: ['version'],
      transitions: [
        StateTransition(fromState: 'failed', toState: 'running', condition: 'success'),
        StateTransition(fromState: 'stopped', toState: 'running', condition: 'success'),
        StateTransition(fromState: 'running', toState: 'failed', condition: 'restore error'),
      ],
    ),
    'create': ActionDef(
      id: 'create',
      displayName: 'Create',
      verb: 'Create',
      pastTense: 'created',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
      optionalPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'inactive', toState: 'active', condition: 'provisioned'),
      ],
    ),
    'delete': ActionDef(
      id: 'delete',
      displayName: 'Delete',
      verb: 'Delete',
      pastTense: 'deleted',
      category: ActionCategory.crud,
      requiredPropertyNames: [],
      optionalPropertyNames: [],
      transitions: [
        StateTransition(fromState: 'active', toState: 'archived', condition: 'soft delete'),
        StateTransition(fromState: 'active', toState: 'stopped', condition: 'terminated'),
      ],
    ),
  },
  stateGraph: StateGraph(
    states: {
      'active': StateDef(id: 'active', displayName: 'Active'),
      'inactive': StateDef(id: 'inactive', displayName: 'Inactive'),
      'pending': StateDef(id: 'pending', displayName: 'Pending'),
      'deploying': StateDef(id: 'deploying', displayName: 'Deploying'),
      'running': StateDef(id: 'running', displayName: 'Running'),
      'failed': StateDef(id: 'failed', displayName: 'Failed'),
      'stopped': StateDef(id: 'stopped', displayName: 'Stopped', isTerminal: true),
      'archived': StateDef(id: 'archived', displayName: 'Archived', isTerminal: true),
      'degraded': StateDef(id: 'degraded', displayName: 'Degraded'),
    },
    transitions: [
      StateTransition(fromState: 'inactive', toState: 'active', condition: 'provisioned'),
      StateTransition(fromState: 'inactive', toState: 'deploying', condition: 'deployment initiated'),
      StateTransition(fromState: 'active', toState: 'inactive', condition: 'decommissioned'),
      StateTransition(fromState: 'active', toState: 'degraded', condition: 'performance degraded'),
      StateTransition(fromState: 'active', toState: 'failed', condition: 'critical error'),
      StateTransition(fromState: 'deploying', toState: 'running', condition: 'deployment succeeded'),
      StateTransition(fromState: 'deploying', toState: 'failed', condition: 'deployment failed'),
      StateTransition(fromState: 'running', toState: 'degraded', condition: 'threshold breached'),
      StateTransition(fromState: 'running', toState: 'stopped', condition: 'shutdown'),
      StateTransition(fromState: 'degraded', toState: 'running', condition: 'recovered'),
      StateTransition(fromState: 'degraded', toState: 'failed', condition: 'critical'),
      StateTransition(fromState: 'failed', toState: 'running', condition: 'restored'),
      StateTransition(fromState: 'failed', toState: 'stopped', condition: 'terminated'),
      StateTransition(fromState: 'pending', toState: 'running', condition: 'ready'),
      StateTransition(fromState: 'pending', toState: 'failed', condition: 'timeout'),
      StateTransition(fromState: 'stopped', toState: 'archived', condition: 'retention expired'),
      StateTransition(fromState: 'active', toState: 'archived', condition: 'soft deleted'),
    ],
  ),
  relationships: [
    OntologyRelationship(sourceEntity: 'server', targetEntity: 'deployment', action: 'deploy'),
    OntologyRelationship(sourceEntity: 'deployment', targetEntity: 'service', action: 'deploy'),
    OntologyRelationship(sourceEntity: 'container', targetEntity: 'server', action: 'deploy'),
    OntologyRelationship(sourceEntity: 'service', targetEntity: 'container', action: 'deploy'),
    OntologyRelationship(sourceEntity: 'server', targetEntity: 'config', action: 'configure'),
    OntologyRelationship(sourceEntity: 'config', targetEntity: 'service', action: 'configure'),
    OntologyRelationship(sourceEntity: 'service', targetEntity: 'metric', action: 'monitor'),
    OntologyRelationship(sourceEntity: 'metric', targetEntity: 'alert', action: 'monitor'),
    OntologyRelationship(sourceEntity: 'log', targetEntity: 'alert', action: 'create'),
    OntologyRelationship(sourceEntity: 'alert', targetEntity: 'service', action: 'monitor'),
    OntologyRelationship(sourceEntity: 'server', targetEntity: 'log', action: 'create'),
    OntologyRelationship(sourceEntity: 'container', targetEntity: 'log', action: 'create'),
    OntologyRelationship(sourceEntity: 'config', targetEntity: 'deployment', action: 'configure'),
    OntologyRelationship(sourceEntity: 'deployment', targetEntity: 'deployment', action: 'backup'),
    OntologyRelationship(sourceEntity: 'deployment', targetEntity: 'deployment', action: 'restore'),
  ],
);
