class DomainData {
  static const Map<String, Map<String, String>> samples = {
    'Identity': {
      'TapLoginField': 'Focus login field',
      'EnterCredentials': 'user@example.com / CorrectP@ss123',
      'TapSubmit': 'Tap Submit button',
      'VerifyDashboard': 'Dashboard loads with user profile visible',
      'ClickLoginButton': 'Locate and click Login button',
      'EnterEmailAndPassword': 'admin@test.com / SecurePass456',
      'ClickSubmit': 'Click Submit/Login button',
      'VerifyLandingPage': 'Landing page shows welcome message',
      'PostAuthPayload': 'POST /auth with {email, password}',
      'ReceiveToken': 'Response includes access_token and refresh_token',
      'VerifyStatusCode200': 'Assert HTTP 200 with valid token payload',
      'TapForgotPassword': 'Tap "Forgot Password" link',
      'EnterEmail': 'registered@example.com',
      'VerifyEmailSent': 'Confirmation toast: "Reset link sent"',
      'ClickResetLink': 'Click password reset link from email',
      'EnterNewPassword': 'NewSecurePass789 / ConfirmNewSecurePass789',
      'ClickConfirm': 'Click Confirm Reset button',
      'VerifySuccessToast': 'Success toast: "Password has been reset"',
    },
    'Commerce': {
      'BrowseCatalog': 'Scroll through product listings',
      'TapAddToCart': 'Tap "Add to Cart" on product: Wireless Headphones',
      'VerifyCartBadge': 'Cart badge updates to show item count',
      'SelectProduct': 'Select first product: SKU-12345',
      'ClickAddToBag': 'Click "Add to Bag" button',
      'VerifyCartSidebar': 'Cart sidebar shows added item with correct price',
      'PostAddToCartPayload': 'POST /cart with {productId, quantity}',
      'VerifyCartCount': 'Assert cart.itemCount == 1',
      'SelectCartItems': 'Cart contains 2 items',
      'ProceedToCheckout': 'Tap "Proceed to Checkout"',
      'EnterPaymentDetails': 'Card: 4111-1111-1111-1111, Exp: 12/28, CVV: 123',
      'SubmitOrder': 'Tap "Place Order" button',
      'TapCartIcon': 'Tap cart icon in header',
      'TapCheckout': 'Tap "Checkout" button',
      'EnterShippingInfo': '123 Main St, City, State 12345',
      'PlaceOrder': 'Tap "Place Order" to confirm',
      'PostCheckoutPayload': 'POST /checkout with {cartId, paymentMethod}',
      'VerifyPaymentResponse': 'Assert payment.status == "success"',
    },
    'Transaction': {
      'TapTransferMenu': 'Navigate to Transfer section',
      'SelectRecipient': 'Select recipient: John Doe (Acct: XXXX-4567)',
      'EnterAmount': '250.00',
      'VerifyOTP': 'Enter OTP: 123456 sent to registered mobile',
      'ClickMoveMoney': 'Click "Move Money" tab',
      'ChooseAccount': 'Select source account: Savings (XXXX-7890)',
      'InputAmount': 'Enter amount: 500.00',
      'ClickConfirm': 'Click "Confirm Transfer" button',
      'PostTransferPayload': 'POST /transfer with {from, to, amount, otp}',
      'VerifyTransactionID': 'Assert response contains valid transactionId',
    },
    'Scheduling': {
      'SelectDates': 'Select: June 15-20, 2026',
      'SubmitRequest': 'Tap "Submit Request" button',
      'VerifyStatus': 'Status shows "Pending Approval"',
      'TapLeaveMenu': 'Tap "Request Leave" menu item',
      'EnterDates': 'Start: 2026-07-01, End: 2026-07-05',
      'TapSubmit': 'Tap Submit button',
    },
    'Records': {
      'NavigateToRecords': 'Go to Records section from main menu',
      'ClickViewDetail': 'Click on record #12345 to view details',
      'VerifyDataLoad': 'Full record data is displayed with all fields',
      'TapDocuments': 'Tap "Documents" tab',
      'OpenPDF': 'Tap to open PDF document viewer',
      'VerifyContentVisibility': 'PDF content renders completely without errors',
    },
    'Integration': {
      'TriggerPipeline': 'POST /pipeline/trigger with {eventType, payload}',
      'MonitorBuild': 'Poll build status endpoint every 5s',
      'VerifyDeployment': 'Assert build.status == "success" and version matches',
    },
  };
}
