class DomainData {
  static const Map<String, Map<String, String>> samples = {
    'Identity': {
      'TapLoginField': 'Focus login field',
      'EnterCredentials': 'member@example.com / CorrectP@ss123',
      'TapSubmit': 'Tap Submit button',
      'VerifyDashboard': 'Dashboard loads with member profile visible',
      'ClickLoginButton': 'Locate and click Login button',
      'EnterEmailAndPassword': 'admin@test.com / SecurePass456',
      'ClickSubmit': 'Click Submit/Login button',
      'VerifyLandingPage': 'Landing page shows welcome message',
      'PostAuthPayload': 'POST /auth with {email, password}',
      'ReceiveToken': 'Response includes access_token and refresh_token',
      'VerifyStatusCode200': 'Assert HTTP 200 with valid token payload',
      'TapForgotPassword': 'Tap "Forgot Password" link',
      'EnterEmail': 'registered@example.com',
      'VerifyEmailSent': 'Confirmation toast: "Reset link sent"',
      'ClickResetLink': 'Click password reset link from email',
      'EnterNewPassword': 'NewSecurePass789 / ConfirmNewSecurePass789',
      'ClickConfirm': 'Click Confirm Reset button',
      'VerifySuccessToast': 'Success toast: "Password has been reset"',
    },
    'Commerce': {
      'BrowseCatalog': 'Scroll through product listings',
      'TapAddToCart': 'Tap "Add to Cart" on product: Wireless Headphones',
      'VerifyCartBadge': 'Cart badge updates to show item count',
      'SelectProduct': 'Select first product: SKU-12345',
      'ClickAddToBag': 'Click "Add to Bag" button',
      'VerifyCartSidebar': 'Cart sidebar shows added item with correct price',
      'PostAddToCartPayload': 'POST /cart with {productId, quantity}',
      'VerifyCartCount': 'Assert cart.itemCount == 1',
      'SelectCartItems': 'Cart contains 2 items',
      'ProceedToCheckout': 'Tap "Proceed to Checkout"',
      'EnterPaymentDetails': 'Card: 4111-1111-1111-1111, Exp: 12/28, CVV: 123',
      'SubmitOrder': 'Tap "Place Order" button',
      'TapCartIcon': 'Tap cart icon in header',
      'TapCheckout': 'Tap "Checkout" button',
      'EnterShippingInfo': '123 Main St, City, State 12345',
      'PlaceOrder': 'Tap "Place Order" to confirm',
      'PostCheckoutPayload': 'POST /checkout with {cartId, paymentMethod}',
      'VerifyPaymentResponse': 'Assert payment.status == "success"',
    },
    'Transaction': {
      'TapTransferMenu': 'Navigate to Transfer section',
      'SelectRecipient': 'Select recipient: John Doe (Acct: XXXX-4567)',
      'EnterAmount': '250.00',
      'VerifyOTP': 'Enter OTP: 123456 sent to registered mobile',
      'ClickMoveMoney': 'Click "Move Money" tab',
      'ChooseAccount': 'Select source account: Savings (XXXX-7890)',
      'InputAmount': 'Enter amount: 500.00',
      'ClickConfirm': 'Click "Confirm Transfer" button',
      'PostTransferPayload': 'POST /transfer with {from, to, amount, otp}',
      'VerifyTransactionID': 'Assert response contains valid transactionId',
    },
    'Scheduling': {
      'NavigateToDateRange': 'Select date range: June 15-20, 2026',
      'SubmitRequestForm': 'Tap "Submit Request" button with complete form',
      'VerifyApprovalStatus': 'Status shows "Pending Approval" with reviewer info',
      'TapLeaveMenu': 'Tap "Request Leave" menu item',
      'EnterLeaveDates': 'Start: 2026-07-01, End: 2026-07-05',
      'TapSubmitRequest': 'Tap Submit Request button to confirm',
    },
    'Records': {
      'NavigateToRecords': 'Go to Records section from main menu',
      'ClickViewDetail': 'Click on record #12345 to view details',
      'VerifyDataLoad': 'Full record data is displayed with all fields',
      'TapDocuments': 'Tap "Documents" tab',
      'OpenPDFDocument': 'Tap to open PDF document viewer',
      'VerifyContentVisibility': 'PDF content renders completely without errors',
      'ClickAddNewRecord': 'Click "Add New Record" button in the header',
      'FillPatientInfo': 'Name: Jane Doe, DOB: 1995-03-22, MRN: MRN-2026-8842',
      'ClickSaveRecord': 'Click "Save Record" to persist the record',
      'VerifyRecordCreated': 'New record REC-2026-0619 appears in the records table',
      'TapRecordsMenu': 'Tap Records tab in the bottom navigation',
      'TapAddRecord': 'Tap "+" icon to add a new patient record',
      'EnterPatientData': 'Patient: Jane Doe, DOB: 1995-03-22, Notes: Annual physical',
      'TapSaveRecord': 'Tap "Save Record" to confirm and persist',
      'VerifyRecordAdded': 'Record added confirmation toast with new record ID',
      'ClickDeleteRecord': 'Click "Delete Record" from the action menu',
      'ConfirmDeletion': 'Type "DELETE" in the confirmation dialog field',
      'VerifyRecordRemoved': 'Record no longer appears in the records list',
      'TapDeleteRecord': 'Tap "Delete Record" from the options menu',
    },
    'Integration': {
      'ClickTriggerPipeline': 'Click to trigger pipeline via POST /pipeline/trigger',
      'MonitorBuildStatus': 'Poll build status endpoint every 5s for completion',
      'VerifyDeploymentSuccess': 'Assert build.status == "success" and version matches',
    },
  };
}
